//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 04:24:15 PM EST 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import com.mofokom.j4mlp.element.Box;
import com.mofokom.j4mlp.element.Cgi;
import com.mofokom.j4mlp.element.CircularArcArea;
import com.mofokom.j4mlp.element.CircularArea;
import com.mofokom.j4mlp.element.Client;
import com.mofokom.j4mlp.element.Coord;
import com.mofokom.j4mlp.element.CoordinateReferenceSystem;
import com.mofokom.j4mlp.element.EllipticalArea;
import com.mofokom.j4mlp.element.EmeEvent;
import com.mofokom.j4mlp.element.EmeLia;
import com.mofokom.j4mlp.element.EmeLir;
import com.mofokom.j4mlp.element.EmePos;
import com.mofokom.j4mlp.element.Emerep;
import com.mofokom.j4mlp.element.Eqop;
import com.mofokom.j4mlp.element.Esrd;
import com.mofokom.j4mlp.element.Esrk;
import com.mofokom.j4mlp.element.Gem;
import com.mofokom.j4mlp.element.GeometryCollection;
import com.mofokom.j4mlp.element.GsmNetParam;
import com.mofokom.j4mlp.element.Identifier;
import com.mofokom.j4mlp.element.LineString;
import com.mofokom.j4mlp.element.LinearRing;
import com.mofokom.j4mlp.element.LocType;
import com.mofokom.j4mlp.element.MsAction;
import com.mofokom.j4mlp.element.Msid;
import com.mofokom.j4mlp.element.MsidRange;
import com.mofokom.j4mlp.element.Msids;
import com.mofokom.j4mlp.element.MultiLineString;
import com.mofokom.j4mlp.element.MultiPoint;
import com.mofokom.j4mlp.element.MultiPolygon;
import com.mofokom.j4mlp.element.Neid;
import com.mofokom.j4mlp.element.ObjectFactory;
import com.mofokom.j4mlp.element.Pd;
import com.mofokom.j4mlp.element.Point;
import com.mofokom.j4mlp.element.Polygon;
import com.mofokom.j4mlp.element.Pos;
import com.mofokom.j4mlp.element.Poserr;
import com.mofokom.j4mlp.element.Prio;
import com.mofokom.j4mlp.element.Pushaddr;
import com.mofokom.j4mlp.element.Qop;
import com.mofokom.j4mlp.element.Requestmode;
import com.mofokom.j4mlp.element.Requestor;
import com.mofokom.j4mlp.element.RespReq;
import com.mofokom.j4mlp.element.Result;
import com.mofokom.j4mlp.element.Session;
import com.mofokom.j4mlp.element.Shape;
import com.mofokom.j4mlp.element.Slia;
import com.mofokom.j4mlp.element.Slir;
import com.mofokom.j4mlp.element.Slirep;
import com.mofokom.j4mlp.element.Slrep;
import com.mofokom.j4mlp.element.StartMsid;
import com.mofokom.j4mlp.element.StartTime;
import com.mofokom.j4mlp.element.StopMsid;
import com.mofokom.j4mlp.element.StopTime;
import com.mofokom.j4mlp.element.Subclient;
import com.mofokom.j4mlp.element.Time;
import com.mofokom.j4mlp.element.Tlra;
import com.mofokom.j4mlp.element.Tlrep;
import com.mofokom.j4mlp.element.Tlrr;
import com.mofokom.j4mlp.element.Tlrsa;
import com.mofokom.j4mlp.element.Tlrsr;
import com.mofokom.j4mlp.element.TrlPos;
import com.mofokom.j4mlp.element.Vlrid;
import com.mofokom.j4mlp.element.Vmscid;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(LocType.class, MultiLineString.class, Slirep.class, Eqop.class, Slrep.class, StopMsid.class, LineString.class, Client.class, Pd.class, CircularArea.class, Session.class, Point.class, CoordinateReferenceSystem.class, Box.class, EmeLia.class, Tlrr.class, Vmscid.class, Requestmode.class, Polygon.class, StopTime.class, Esrd.class, MsAction.class, GsmNetParam.class, Esrk.class, Requestor.class, Emerep.class, RespReq.class, Msids.class, EmeLir.class, Tlra.class, LinearRing.class, Gem.class, EmePos.class, Pos.class, CircularArcArea.class, Slir.class, MultiPoint.class, Slia.class, EmeEvent.class, Qop.class, StartTime.class, TrlPos.class, Cgi.class, Tlrsa.class, Msid.class, GeometryCollection.class, Neid.class, Pushaddr.class, Subclient.class, Vlrid.class, Poserr.class, Tlrsr.class, MsidRange.class, Identifier.class, Prio.class, StartMsid.class, Time.class, EllipticalArea.class, MultiPolygon.class, Coord.class, Tlrep.class, Shape.class, Result.class, ObjectFactory.class);
    }

}
