//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 11:58:16 AM CEST 
//


package mofokom.xmlrpc;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public class DateConverter
{

    private static SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd'T'HH:mm:ssZZZ");
    public static Calendar parseDate(String value) {
        Calendar cal =  Calendar.getInstance();
        try {
            cal.setTime(sdf.parse(value));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        return cal;
    }

    public static String printDate(Calendar value) {
        if (value == null) {
            return null;
        }
        return sdf.format(value.getTime());
    }

}
