/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mofokom.in.mgcp.resource.impl;

/**
 *
 * @author wozza
 */
public class StatusCode {
    /*
     * 000 Response Acknowledgement.

   100 The transaction is currently being executed.  An actual
       completion message will follow later.

   101 The transaction has been queued for execution.  An actual
       completion message will follow later.

   200 The requested transaction was executed normally.  This return
       code can be used for a successful response to any command.

   250 The connection was deleted.  This return code can only be used
       for a successful response to a DeleteConnection command.

   400 The transaction could not be executed, due to some unspecified
       transient error.

   401 The phone is already off hook.

   402 The phone is already on hook.

   403 The transaction could not be executed, because the endpoint does
       not have sufficient resources at this time.

   404 Insufficient bandwidth at this time.

   405 The transaction could not be executed, because the endpoint is
       "restarting".

   406 Transaction time-out.  The transaction did not complete in a
       reasonable period of time and has been aborted.

   407 Transaction aborted.  The transaction was aborted by some
       external action, e.g., a ModifyConnection command aborted by a
       DeleteConnection command.

   409 The transaction could not be executed because of internal
       overload.

   410 No endpoint available.  A valid "any of" wildcard was used,
       however there was no endpoint available to satisfy the request.

   500 The transaction could not be executed, because the endpoint is
       unknown.

   501 The transaction could not be executed, because the endpoint is
       not ready.  This includes the case where the endpoint is out-of-
       service.

   502 The transaction could not be executed, because the endpoint does
       not have sufficient resources (permanent condition).

   503 "All of" wildcard too complicated.

   504 Unknown or unsupported command.

   505 Unsupported RemoteConnectionDescriptor.  This SHOULD be used when
       one or more mandatory parameters or values in the
       RemoteConnectionDescriptor is not supported.

   506 Unable to satisfy both LocalConnectionOptions and
       RemoteConnectionDescriptor.  This SHOULD be used when the
       LocalConnectionOptions and RemoteConnectionDescriptor contain one
       or more mandatory parameters or values that conflict with each
       other and/or cannot be supported at the same time (except for
       codec negotiation failure - see error code 534).

   507 Unsupported functionality. Some unspecified functionality
       required to carry out the command is not supported. Note that
       several other error codes have been defined for specific areas of
       unsupported functionality (e.g. 508, 511, etc.), and this error
       code SHOULD only be used if there is no other more specific error
       code for the unsupported functionality.

   508 Unknown or unsupported quarantine handling.

   509 Error in RemoteConnectionDescriptor.  This SHOULD be used when
       there is a syntax or semantic error in the
       RemoteConnectionDescriptor.

   510 The transaction could not be executed, because some unspecified
       protocol error was detected.  Automatic recovery from such an
       error will be very difficult, and hence this code SHOULD only be
       used as a last resort.

   511 The transaction could not be executed, because the command
       contained an unrecognized extension.  This code SHOULD be used
       for unsupported critical parameter extensions ("X+").

   512 The transaction could not be executed, because the gateway is not
       equipped to detect one of the requested events.

   513 The transaction could not be executed, because the gateway is not
       equipped to generate one of the requested signals.

   514 The transaction could not be executed, because the gateway cannot
       send the specified announcement.

   515 The transaction refers to an incorrect connection-id (may have
       been already deleted).

   516 The transaction refers to an unknown call-id, or the call-id
       supplied is incorrect (e.g., connection-id not associated with
       this call-id).

   517 Unsupported or invalid mode.

   518 Unsupported or unknown package.  It is RECOMMENDED to include a
       PackageList parameter with the list of supported packages in the
       response, especially if the response is generated by the Call
       Agent.

   519 Endpoint does not have a digit map.

   520 The transaction could not be executed, because the endpoint is
       "restarting".  In most cases this would be a transient error, in
       which case, error code 405 SHOULD be used instead.  The error
       code is only included here for backwards compatibility.

   521 Endpoint redirected to another Call Agent.  The associated
       redirection behavior is only well-defined when this response is
       issued for a RestartInProgress command.

   522 No such event or signal.  The request referred to an event or
       signal that is not defined in the relevant package (which could
       be the default package).

   523 Unknown action or illegal combination of actions.

   524 Internal inconsistency in LocalConnectionOptions.

   525 Unknown extension in LocalConnectionOptions.  This code SHOULD be
       used for unsupported mandatory vendor extensions ("x+").

   526 Insufficient bandwidth.  In cases where this is a transient
       error, error code 404 SHOULD be used instead.

   527 Missing RemoteConnectionDescriptor.

   528 Incompatible protocol version.

   529 Internal hardware failure.

   530 CAS signaling protocol error.

   531 Failure of a grouping of trunks (e.g., facility failure).

   532 Unsupported value(s) in LocalConnectionOptions.

   533 Response too large.

   534 Codec negotiation failure.

   535 Packetization period not supported.

   536 Unknown or unsupported RestartMethod.

   537 Unknown or unsupported digit map extension.

   538 Event/signal parameter error (e.g., missing, erroneous,
       unsupported, unknown, etc.).

   539 Invalid or unsupported command parameter. This code SHOULD only
       be used when the parameter is neither a package or vendor
       extension parameter.

   540 Per endpoint connection limit exceeded.

   541 Invalid or unsupported LocalConnectionOptions. This code SHOULD
       only be used when the LocalConnectionOptions is neither a package
       nor a vendor extension LocalConnectionOptions.

   The set of return codes may be extended in a future version of the
   protocol.  Implementations that receive an unknown or unsupported
   return code SHOULD treat the return code as follows:
     */
}
