CREATE TABLE MyTestEntity (id BIGINT NOT NULL, Other VARCHAR(255), stamp ABSTIME, value VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE OPENMLP_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
