/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mofokom.in.ussd.resource.impl;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author wozza
 */
public class ErrorCodes {

    Map<Integer, String> map = new HashMap<Integer, String>();

    ErrorCodes() {
        map.put(Integer.valueOf(0)," No Error");
        map.put(Integer.valueOf(1)," The subscriber is unknown");
        map.put(Integer.valueOf(2)," The Base_station is unknown");
        map.put(Integer.valueOf(3)," The MSC is unknown");
        map.put(Integer.valueOf(4)," The Loc_area is unknown");
        map.put(Integer.valueOf(5)," The subscriber is undentified");
        map.put(Integer.valueOf(6)," The roaming number is unallocated");
        map.put(Integer.valueOf(7)," The equipment is unknown");
        map.put(Integer.valueOf(8)," The roaming is not be allowed");
        map.put(Integer.valueOf(9)," The MS is illegal");
        map.put(Integer.valueOf(10)," The bearer service is not be provided");
        map.put(Integer.valueOf(11)," The television is not be provided");
        map.put(Integer.valueOf(12)," The bearer capability is not sufficient or the equitment is illegal");
        map.put(Integer.valueOf(13)," The call has been barred");
        map.put(Integer.valueOf(14)," The forwarding is violated");
        map.put(Integer.valueOf(15)," The CUG reject");
        map.put(Integer.valueOf(16)," The SS operation is illegal");
        map.put(Integer.valueOf(17)," The state is SS_error");
        map.put(Integer.valueOf(18)," The SS is not available");
        map.put(Integer.valueOf(19)," The SS_Subscription is violated");
        map.put(Integer.valueOf(20)," The SS is incompatible");
        map.put(Integer.valueOf(21)," The facility is not supported");
        map.put(Integer.valueOf(23)," The target_base_station is invalid");
        map.put(Integer.valueOf(24)," There is not the available radio resourse");
        map.put(Integer.valueOf(25)," There is nor the available handover number");
        map.put(Integer.valueOf(26)," The subsequent handover is failure");
        map.put(Integer.valueOf(27)," The subscriber is absent");
        map.put(Integer.valueOf(29)," The subscriber is busy");
        map.put(Integer.valueOf(30)," The radio is congested");
        map.put(Integer.valueOf(31)," The call is impossible completed or the subscriber for MT_SMS is busy");
        map.put(Integer.valueOf(32)," The SM_delivery is failure");
        map.put(Integer.valueOf(33)," The message_waiting_list is full");
        map.put(Integer.valueOf(34)," The system is failure");
        map.put(Integer.valueOf(35)," The data is missed");
        map.put(Integer.valueOf(36)," The date value is unexpected");
        map.put(Integer.valueOf(37)," The passward registion is failed");
        map.put(Integer.valueOf(38)," The passward check is not pass");
        map.put(Integer.valueOf(39)," There is not the roaming number");
        map.put(Integer.valueOf(40)," The tracing buffer is full");
        map.put(Integer.valueOf(43)," The num of PW attempts is violated");
        map.put(Integer.valueOf(44)," The map_number has changed");
        map.put(Integer.valueOf(50)," The error is in MS");
        map.put(Integer.valueOf(51)," The SMS_Lower_layers capability is not provided");
        map.put(Integer.valueOf(52)," The memory has exceeded");
        map.put(Integer.valueOf(53)," The SC is congested");
        map.put(Integer.valueOf(54)," The MS is not a SC subscriber");
        map.put(Integer.valueOf(55)," The SME address is invalid");
        map.put(Integer.valueOf(56)," The subscriber without para is absent");
        map.put(Integer.valueOf(253)," The dialog creation is failed");
        map.put(Integer.valueOf(254)," The MS is released");
        map.put(Integer.valueOf(1001)," Account is not found or does not exist");
        map.put(Integer.valueOf(1002)," Account type is not valid");
        map.put(Integer.valueOf(1003)," The account has been bound too many users");
        map.put(Integer.valueOf(1004)," The account has already existed");
        map.put(Integer.valueOf(1005)," The account does not exist");
        map.put(Integer.valueOf(1006)," The account to be modified conflicked with the exist ones");
        map.put(Integer.valueOf(1007)," The account is in use now");
        map.put(Integer.valueOf(1008)," The account count has reached its limit");
        map.put(Integer.valueOf(1009)," The password is not valid");
        map.put(Integer.valueOf(1010)," The service count has reached its limit");
        map.put(Integer.valueOf(1011)," The interface count has reached its limit");
        map.put(Integer.valueOf(1012)," The service can not be found");
        map.put(Integer.valueOf(1013)," The service number is not valid");
        map.put(Integer.valueOf(1014)," The interface can not be found");
        map.put(Integer.valueOf(1015)," The OMC Server can not monitored");
        map.put(Integer.valueOf(1016)," Interface can not monitor itself");
        map.put(Integer.valueOf(1017)," The task count has reached its limit");
        map.put(Integer.valueOf(1018)," The task can not be found");
        map.put(Integer.valueOf(1019)," The statistic tasks count has reached its limit");
        map.put(Integer.valueOf(1020)," The Ussd Dialogs count has reached its limit");
        map.put(Integer.valueOf(1021)," The Ussd Dialog can not be found");
        map.put(Integer.valueOf(1022)," The Ussd sring seems in bad format");
        map.put(Integer.valueOf(1023)," The Ussd Entity has exit");
        map.put(Integer.valueOf(1024)," Ussd Switch operation has failed");
        map.put(Integer.valueOf(1025)," END_LOAD_USER message recieved while the loading operation has not completed");
        map.put(Integer.valueOf(1026)," The user loader has already existed");
        map.put(Integer.valueOf(1027)," Max user request count has been reached");
        map.put(Integer.valueOf(1028)," Max user count has been reached");
        map.put(Integer.valueOf(1029)," The User has already exist");
        map.put(Integer.valueOf(1030)," User can not be found");
        map.put(Integer.valueOf(1031)," Package was currupted");
        map.put(Integer.valueOf(1032)," Create failed (usually refers to 'not enough memory')");
        map.put(Integer.valueOf(1033)," Insufficient rights");
        map.put(Integer.valueOf(1034)," Operation time out");
        map.put(Integer.valueOf(1035)," Invalid parameters");
        map.put(Integer.valueOf(1036)," Internal error");
        map.put(Integer.valueOf(1037)," The max server information count has been reached");
        map.put(Integer.valueOf(1038)," The Server informaion can not be found");
        map.put(Integer.valueOf(1039)," The server information has already exist");
        map.put(Integer.valueOf(1040)," The file that contains the server information can not be found");
        map.put(Integer.valueOf(1041)," The snapshot has already exist");
        map.put(Integer.valueOf(1042)," The snapshot can not be found");
        map.put(Integer.valueOf(1043)," The service code can not be found in the route table");
        map.put(Integer.valueOf(1044)," There is no bind info can be found in the route table");
        map.put(Integer.valueOf(1045)," There is no interface bounded in this number segment");
        map.put(Integer.valueOf(1046)," The account is not a service account");
        map.put(Integer.valueOf(1047)," The account does not support any service");
        map.put(Integer.valueOf(1048)," The number segment can not be found");
        map.put(Integer.valueOf(1049)," There is no such authentication type");
        map.put(Integer.valueOf(1050)," Authentication failed");
        map.put(Integer.valueOf(1051)," Query thread info operation failed");
        map.put(Integer.valueOf(1052)," Interface can not be found");
        map.put(Integer.valueOf(1053)," Unknown error");
        map.put(Integer.valueOf(1054)," Illegal server type");
        map.put(Integer.valueOf(1055)," There is no MSISDN in the message and MSISDN can not be found based on the IMSI");
        map.put(Integer.valueOf(1056)," Interface has already blocked ");
        map.put(Integer.valueOf(1057)," Dialog Time Out");
        map.put(Integer.valueOf(1058)," Exceed Max Scp Account Count");
        map.put(Integer.valueOf(1059)," Scp Account existed");
        map.put(Integer.valueOf(1060)," Scp Account not existed");
        map.put(Integer.valueOf(1061)," Can not modify Scp Account with ScpIF");
        map.put(Integer.valueOf(1062)," IP and Port of Scp Account existed");
        map.put(Integer.valueOf(1063)," Scp Account conflicted");
        map.put(Integer.valueOf(1064)," Exceed Max IF Count of SCP Account");
        map.put(Integer.valueOf(1065)," ScpIF not existed");
        map.put(Integer.valueOf(1066)," ScpIF Logined with this account existed");
        map.put(Integer.valueOf(1067)," Delete ScpIF Error");
        map.put(Integer.valueOf(1068)," Invalid ScpIF Param");
        map.put(Integer.valueOf(1069)," Create ScpIF Failure");
        map.put(Integer.valueOf(1070)," Delete PPS Nosegment Error");
        map.put(Integer.valueOf(1071)," Add PPS Nosegment Error");
        map.put(Integer.valueOf(1072)," Modify PPS Nosegment Error");
        map.put(Integer.valueOf(1073)," PPS Nosegment not existed");
        map.put(Integer.valueOf(1074)," PPS Route not found");
        map.put(Integer.valueOf(1075)," PPS Nosegment existed");
        map.put(Integer.valueOf(1076)," Scp CommFee Auth Failed");
        map.put(Integer.valueOf(1077)," Scp InfoFee Auth Failed");
        map.put(Integer.valueOf(1078)," Scp Connect Failed");
        map.put(Integer.valueOf(1079)," Scp Timeout");
        map.put(Integer.valueOf(1080)," Not PPS User");
        map.put(Integer.valueOf(1081)," Auth failed because can't find route");
        map.put(Integer.valueOf(1082)," Auth failed because can't find servicecode");
        map.put(Integer.valueOf(1083)," Auth failed because can't find user");
        map.put(Integer.valueOf(1084)," MS invalid operation");
        map.put(Integer.valueOf(1085)," Sp charge again");
        map.put(Integer.valueOf(1086)," Is PPS User");
        map.put(Integer.valueOf(1087)," Service Code is in use");
        map.put(Integer.valueOf(1088)," Ussd Dialog reach maximum interactive count");
        map.put(Integer.valueOf(1089)," USSD dialog switch failed");
        map.put(Integer.valueOf(2001)," Invalid SPID");
        map.put(Integer.valueOf(2002)," Wrong Auth Information");
        map.put(Integer.valueOf(2003)," Reach maximum dialogs");
        map.put(Integer.valueOf(2004)," Can't find dialog");
        map.put(Integer.valueOf(2005)," Switch dialog failed");
        map.put(Integer.valueOf(2006)," MS response timeout");
        map.put(Integer.valueOf(2007)," SP response timeout");
        map.put(Integer.valueOf(2008)," Dialog response timeout");
        map.put(Integer.valueOf(2009)," No matched route");
        map.put(Integer.valueOf(2010)," Dialog version is wrong");
        map.put(Integer.valueOf(2011)," Dialog type is wrong");
        map.put(Integer.valueOf(2012)," Format of UssdString is wrong");
        map.put(Integer.valueOf(2013)," Service Access number is wrong");
        map.put(Integer.valueOf(2014)," Invalid User");
        map.put(Integer.valueOf(2015)," Map_Open failed");
        map.put(Integer.valueOf(2016)," Map_Open failed");
        map.put(Integer.valueOf(2017)," MS release call");
        map.put(Integer.valueOf(2018)," MS network breakdown");
        map.put(Integer.valueOf(2019)," UAP Version is too high");
        map.put(Integer.valueOf(2020)," User has no enough balance");
        map.put(Integer.valueOf(2021)," Can't find Service Information");
        map.put(Integer.valueOf(2022)," Fail to lookup");
        map.put(Integer.valueOf(5001)," Client systems have not been initiated");
        map.put(Integer.valueOf(5002)," client systems already been initiated");
        map.put(Integer.valueOf(5003)," Object create failure");
        map.put(Integer.valueOf(5004)," Handle not found");
        map.put(Integer.valueOf(5005)," No message or message queue is empty");
        map.put(Integer.valueOf(5006)," Login failure for invalid account or password");
        map.put(Integer.valueOf(5007)," Invalid parameters");
        map.put(Integer.valueOf(5008)," Internal error");
        map.put(Integer.valueOf(5009)," Time out error");
        map.put(Integer.valueOf(5010)," Null Object");
        map.put(Integer.valueOf(5011)," Reach maximum interface count");
        map.put(Integer.valueOf(5012)," Reach maximum ussddialog count");
        map.put(Integer.valueOf(5013)," Ussddialog object has not been initiated");
        map.put(Integer.valueOf(5014)," Ussddialog not found");
        map.put(Integer.valueOf(5015)," Ussddialog version error");
        map.put(Integer.valueOf(5016)," Message is null or message length error");
        map.put(Integer.valueOf(5017)," Current message is not from service");
        map.put(Integer.valueOf(5018)," Current message is not from MS");
        map.put(Integer.valueOf(5019)," Invalid ussddialog message operation type");
        map.put(Integer.valueOf(5020)," Client close dialog");
        map.put(Integer.valueOf(5021)," Callback functions not registered");
        map.put(Integer.valueOf(5022)," Message not supported by current status");
        map.put(Integer.valueOf(5023)," Invalid callback functions");
        map.put(Integer.valueOf(5024)," Reach maximum thread called count");
        map.put(Integer.valueOf(5025)," Invalid function calling");
        map.put(Integer.valueOf(5026)," Invalid MSISDN");
        map.put(Integer.valueOf(5027)," Invalid TimeOut");
        map.put(Integer.valueOf(6001)," Account is not found or does not exist");
        map.put(Integer.valueOf(6002)," Account type is not valid");
        map.put(Integer.valueOf(6003)," The account has been bound too many users");
        map.put(Integer.valueOf(6004)," The account has been existed");
        map.put(Integer.valueOf(6005)," The account does not exist");
        map.put(Integer.valueOf(6006)," The account to be modified conflicked with the exist ones");
        map.put(Integer.valueOf(6007)," The account is in use now");
        map.put(Integer.valueOf(6008)," The account has reached its limit");
        map.put(Integer.valueOf(6009)," The password is not valid");
        map.put(Integer.valueOf(6010)," The service count has reached its limit");
        map.put(Integer.valueOf(6011)," The interface count has reached its limit");
        map.put(Integer.valueOf(6012)," The service can not be fount");
        map.put(Integer.valueOf(6013)," The service number is not valid");
        map.put(Integer.valueOf(6014)," The interface can not be found");
        map.put(Integer.valueOf(6015)," The OMC Server can not be minitored");
        map.put(Integer.valueOf(6016)," Interface can not monitor itself");
        map.put(Integer.valueOf(6017)," The task count has reached its limit");
        map.put(Integer.valueOf(6018)," The task can not be found");
        map.put(Integer.valueOf(6019)," The statistic tasks count has reached its limit");
        map.put(Integer.valueOf(6020)," The Ussd Dialogs count has reached its limit");
        map.put(Integer.valueOf(6021)," The Ussd Dialog can not be found");
        map.put(Integer.valueOf(6022)," The Ussd string seems in bad format");
        map.put(Integer.valueOf(6023)," The Ussd Entity has exit");
        map.put(Integer.valueOf(6024)," Ussd Switch operation has failed");
        map.put(Integer.valueOf(6025)," END_LOAD_USER message recerved while the loading operation has not completed");
        map.put(Integer.valueOf(6026)," The user loader has already existed");
        map.put(Integer.valueOf(6027)," Max user requesr count has been reached");
        map.put(Integer.valueOf(6028)," Max user count has been reached");
        map.put(Integer.valueOf(6030)," User can not been found");
        map.put(Integer.valueOf(6031)," Package was currupted");
        map.put(Integer.valueOf(6032)," Create failed(usually refers to 'not enough memory')");
        map.put(Integer.valueOf(6033)," Insufficient rights");
        map.put(Integer.valueOf(6034)," Operation time out");
        map.put(Integer.valueOf(6035)," Invalid parameters");
        map.put(Integer.valueOf(6036)," Internal error");
        map.put(Integer.valueOf(6037)," The max server information count has been reached");
        map.put(Integer.valueOf(6038)," The Server information can not be found");
        map.put(Integer.valueOf(6039)," The server information has already exist");
        map.put(Integer.valueOf(6040)," The file that contains the server information can not be found");
        map.put(Integer.valueOf(6041)," The snapshot has already exist");
        map.put(Integer.valueOf(6042)," The snapshot can not be found");
        map.put(Integer.valueOf(6043)," The service code can not be found in the route table");
        map.put(Integer.valueOf(6044)," There is no bind info can be found about this account");
        map.put(Integer.valueOf(6045)," There is no interface bounded in this number segment");
        map.put(Integer.valueOf(6046)," The account is not a service account");
        map.put(Integer.valueOf(6047)," The account doed not support any service");
        map.put(Integer.valueOf(6048)," The number segment can not be found");
        map.put(Integer.valueOf(6049)," There is no such authentication type");
        map.put(Integer.valueOf(6050)," Authentication failed");
        map.put(Integer.valueOf(6051)," Query thread info operation failed");
        map.put(Integer.valueOf(6052)," Interface can not be found");
        map.put(Integer.valueOf(6053)," Unknown error");
        map.put(Integer.valueOf(6054)," Invalid server type");
        map.put(Integer.valueOf(6055)," Interface has already blocked");
    }

    public String getErrorMessage(int code) {
        return map.get(Integer.valueOf(code));
    }
}
