	
          package mofokom.ccn.air.acip.resource;
          import javax.annotation.Generated;
          import javax.slee.usage.SampleStatistics;
          import mofokom.ccn.resource.ResourceAdaptorUsageParameters;
          @Generated(value={})
          public interface ACIPResourceAdaptorUsageParameters extends ResourceAdaptorUsageParameters {
        public void incrementTxOK(long l) ;
        public void incrementRxOK(long l) ;
        public void incrementTxNOK(long l) ;
        public void incrementRxNOK(long l) ;
        public long getTxOK() ;
        public long getRxOK() ;
        public long getTxNOK() ;
        public long getRxNOK() ;
        public SampleStatistics getLatencyTxOK() ;
        public SampleStatistics getLatencyRxOK() ;
        public SampleStatistics getLatencyTxNOK() ;
        public SampleStatistics getLatencyRxNOK() ;
        public void sampleLatencyTxOK(long l) ;
        public void sampleLatencyRxOK(long l) ;
        public void sampleLatencyTxNOK(long l) ;
        public void sampleLatencyRxNOK(long l) ;
        public void incrementFaultTxOK(long l) ;
        public void incrementFaultRxOK(long l) ;
        public void incrementFaultTxNOK(long l) ;
        public void incrementFaultRxNOK(long l) ;
        public long getFaultTxOK() ;
        public long getFaultRxOK() ;
        public long getFaultTxNOK() ;
        public long getFaultRxNOK() ;
        public SampleStatistics getFaultLatencyTxOK() ;
        public SampleStatistics getFaultLatencyRxOK() ;
        public SampleStatistics getFaultLatencyTxNOK() ;
        public SampleStatistics getFaultLatencyRxNOK() ;
        public void sampleFaultLatencyTxOK(long l) ;
        public void sampleFaultLatencyRxOK(long l) ;
        public void sampleFaultLatencyTxNOK(long l) ;
        public void sampleFaultLatencyRxNOK(long l) ;
	
        public void incrementUpdateTemporaryBlockedTxOK(long l) ;
        public void incrementUpdateTemporaryBlockedRxOK(long l) ;
        public void incrementUpdateTemporaryBlockedTxNOK(long l) ;
        public void incrementUpdateTemporaryBlockedRxNOK(long l) ;
        public long getUpdateTemporaryBlockedTxOK() ;
        public long getUpdateTemporaryBlockedRxOK() ;
        public long getUpdateTemporaryBlockedTxNOK() ;
        public long getUpdateTemporaryBlockedRxNOK() ;
        public SampleStatistics getUpdateTemporaryBlockedLatencyTxOK() ;
        public SampleStatistics getUpdateTemporaryBlockedLatencyRxOK() ;
        public SampleStatistics getUpdateTemporaryBlockedLatencyTxNOK() ;
        public SampleStatistics getUpdateTemporaryBlockedLatencyRxNOK() ;
        public void sampleUpdateTemporaryBlockedLatencyTxOK(long l) ;
        public void sampleUpdateTemporaryBlockedLatencyRxOK(long l) ;
        public void sampleUpdateTemporaryBlockedLatencyTxNOK(long l) ;
        public void sampleUpdateTemporaryBlockedLatencyRxNOK(long l) ;
	
        public void incrementUpdateRefillBarringTxOK(long l) ;
        public void incrementUpdateRefillBarringRxOK(long l) ;
        public void incrementUpdateRefillBarringTxNOK(long l) ;
        public void incrementUpdateRefillBarringRxNOK(long l) ;
        public long getUpdateRefillBarringTxOK() ;
        public long getUpdateRefillBarringRxOK() ;
        public long getUpdateRefillBarringTxNOK() ;
        public long getUpdateRefillBarringRxNOK() ;
        public SampleStatistics getUpdateRefillBarringLatencyTxOK() ;
        public SampleStatistics getUpdateRefillBarringLatencyRxOK() ;
        public SampleStatistics getUpdateRefillBarringLatencyTxNOK() ;
        public SampleStatistics getUpdateRefillBarringLatencyRxNOK() ;
        public void sampleUpdateRefillBarringLatencyTxOK(long l) ;
        public void sampleUpdateRefillBarringLatencyRxOK(long l) ;
        public void sampleUpdateRefillBarringLatencyTxNOK(long l) ;
        public void sampleUpdateRefillBarringLatencyRxNOK(long l) ;
	
        public void incrementUpdatePromotionPlanTxOK(long l) ;
        public void incrementUpdatePromotionPlanRxOK(long l) ;
        public void incrementUpdatePromotionPlanTxNOK(long l) ;
        public void incrementUpdatePromotionPlanRxNOK(long l) ;
        public long getUpdatePromotionPlanTxOK() ;
        public long getUpdatePromotionPlanRxOK() ;
        public long getUpdatePromotionPlanTxNOK() ;
        public long getUpdatePromotionPlanRxNOK() ;
        public SampleStatistics getUpdatePromotionPlanLatencyTxOK() ;
        public SampleStatistics getUpdatePromotionPlanLatencyRxOK() ;
        public SampleStatistics getUpdatePromotionPlanLatencyTxNOK() ;
        public SampleStatistics getUpdatePromotionPlanLatencyRxNOK() ;
        public void sampleUpdatePromotionPlanLatencyTxOK(long l) ;
        public void sampleUpdatePromotionPlanLatencyRxOK(long l) ;
        public void sampleUpdatePromotionPlanLatencyTxNOK(long l) ;
        public void sampleUpdatePromotionPlanLatencyRxNOK(long l) ;
	
        public void incrementGetPromotionPlansTxOK(long l) ;
        public void incrementGetPromotionPlansRxOK(long l) ;
        public void incrementGetPromotionPlansTxNOK(long l) ;
        public void incrementGetPromotionPlansRxNOK(long l) ;
        public long getGetPromotionPlansTxOK() ;
        public long getGetPromotionPlansRxOK() ;
        public long getGetPromotionPlansTxNOK() ;
        public long getGetPromotionPlansRxNOK() ;
        public SampleStatistics getGetPromotionPlansLatencyTxOK() ;
        public SampleStatistics getGetPromotionPlansLatencyRxOK() ;
        public SampleStatistics getGetPromotionPlansLatencyTxNOK() ;
        public SampleStatistics getGetPromotionPlansLatencyRxNOK() ;
        public void sampleGetPromotionPlansLatencyTxOK(long l) ;
        public void sampleGetPromotionPlansLatencyRxOK(long l) ;
        public void sampleGetPromotionPlansLatencyTxNOK(long l) ;
        public void sampleGetPromotionPlansLatencyRxNOK(long l) ;
	
        public void incrementPromotionPlanInformationTxOK(long l) ;
        public void incrementPromotionPlanInformationRxOK(long l) ;
        public void incrementPromotionPlanInformationTxNOK(long l) ;
        public void incrementPromotionPlanInformationRxNOK(long l) ;
        public long getPromotionPlanInformationTxOK() ;
        public long getPromotionPlanInformationRxOK() ;
        public long getPromotionPlanInformationTxNOK() ;
        public long getPromotionPlanInformationRxNOK() ;
        public SampleStatistics getPromotionPlanInformationLatencyTxOK() ;
        public SampleStatistics getPromotionPlanInformationLatencyRxOK() ;
        public SampleStatistics getPromotionPlanInformationLatencyTxNOK() ;
        public SampleStatistics getPromotionPlanInformationLatencyRxNOK() ;
        public void samplePromotionPlanInformationLatencyTxOK(long l) ;
        public void samplePromotionPlanInformationLatencyRxOK(long l) ;
        public void samplePromotionPlanInformationLatencyTxNOK(long l) ;
        public void samplePromotionPlanInformationLatencyRxNOK(long l) ;
	
        public void incrementUpdateAccumulatorsTxOK(long l) ;
        public void incrementUpdateAccumulatorsRxOK(long l) ;
        public void incrementUpdateAccumulatorsTxNOK(long l) ;
        public void incrementUpdateAccumulatorsRxNOK(long l) ;
        public long getUpdateAccumulatorsTxOK() ;
        public long getUpdateAccumulatorsRxOK() ;
        public long getUpdateAccumulatorsTxNOK() ;
        public long getUpdateAccumulatorsRxNOK() ;
        public SampleStatistics getUpdateAccumulatorsLatencyTxOK() ;
        public SampleStatistics getUpdateAccumulatorsLatencyRxOK() ;
        public SampleStatistics getUpdateAccumulatorsLatencyTxNOK() ;
        public SampleStatistics getUpdateAccumulatorsLatencyRxNOK() ;
        public void sampleUpdateAccumulatorsLatencyTxOK(long l) ;
        public void sampleUpdateAccumulatorsLatencyRxOK(long l) ;
        public void sampleUpdateAccumulatorsLatencyTxNOK(long l) ;
        public void sampleUpdateAccumulatorsLatencyRxNOK(long l) ;
	
        public void incrementAccumulatorInformationTxOK(long l) ;
        public void incrementAccumulatorInformationRxOK(long l) ;
        public void incrementAccumulatorInformationTxNOK(long l) ;
        public void incrementAccumulatorInformationRxNOK(long l) ;
        public long getAccumulatorInformationTxOK() ;
        public long getAccumulatorInformationRxOK() ;
        public long getAccumulatorInformationTxNOK() ;
        public long getAccumulatorInformationRxNOK() ;
        public SampleStatistics getAccumulatorInformationLatencyTxOK() ;
        public SampleStatistics getAccumulatorInformationLatencyRxOK() ;
        public SampleStatistics getAccumulatorInformationLatencyTxNOK() ;
        public SampleStatistics getAccumulatorInformationLatencyRxNOK() ;
        public void sampleAccumulatorInformationLatencyTxOK(long l) ;
        public void sampleAccumulatorInformationLatencyRxOK(long l) ;
        public void sampleAccumulatorInformationLatencyTxNOK(long l) ;
        public void sampleAccumulatorInformationLatencyRxNOK(long l) ;
	
        public void incrementInstallSubscriberTxOK(long l) ;
        public void incrementInstallSubscriberRxOK(long l) ;
        public void incrementInstallSubscriberTxNOK(long l) ;
        public void incrementInstallSubscriberRxNOK(long l) ;
        public long getInstallSubscriberTxOK() ;
        public long getInstallSubscriberRxOK() ;
        public long getInstallSubscriberTxNOK() ;
        public long getInstallSubscriberRxNOK() ;
        public SampleStatistics getInstallSubscriberLatencyTxOK() ;
        public SampleStatistics getInstallSubscriberLatencyRxOK() ;
        public SampleStatistics getInstallSubscriberLatencyTxNOK() ;
        public SampleStatistics getInstallSubscriberLatencyRxNOK() ;
        public void sampleInstallSubscriberLatencyTxOK(long l) ;
        public void sampleInstallSubscriberLatencyRxOK(long l) ;
        public void sampleInstallSubscriberLatencyTxNOK(long l) ;
        public void sampleInstallSubscriberLatencyRxNOK(long l) ;
	
        public void incrementDeleteSubscriberTxOK(long l) ;
        public void incrementDeleteSubscriberRxOK(long l) ;
        public void incrementDeleteSubscriberTxNOK(long l) ;
        public void incrementDeleteSubscriberRxNOK(long l) ;
        public long getDeleteSubscriberTxOK() ;
        public long getDeleteSubscriberRxOK() ;
        public long getDeleteSubscriberTxNOK() ;
        public long getDeleteSubscriberRxNOK() ;
        public SampleStatistics getDeleteSubscriberLatencyTxOK() ;
        public SampleStatistics getDeleteSubscriberLatencyRxOK() ;
        public SampleStatistics getDeleteSubscriberLatencyTxNOK() ;
        public SampleStatistics getDeleteSubscriberLatencyRxNOK() ;
        public void sampleDeleteSubscriberLatencyTxOK(long l) ;
        public void sampleDeleteSubscriberLatencyRxOK(long l) ;
        public void sampleDeleteSubscriberLatencyTxNOK(long l) ;
        public void sampleDeleteSubscriberLatencyRxNOK(long l) ;
	
        public void incrementLinkSubordinateSubscriberTxOK(long l) ;
        public void incrementLinkSubordinateSubscriberRxOK(long l) ;
        public void incrementLinkSubordinateSubscriberTxNOK(long l) ;
        public void incrementLinkSubordinateSubscriberRxNOK(long l) ;
        public long getLinkSubordinateSubscriberTxOK() ;
        public long getLinkSubordinateSubscriberRxOK() ;
        public long getLinkSubordinateSubscriberTxNOK() ;
        public long getLinkSubordinateSubscriberRxNOK() ;
        public SampleStatistics getLinkSubordinateSubscriberLatencyTxOK() ;
        public SampleStatistics getLinkSubordinateSubscriberLatencyRxOK() ;
        public SampleStatistics getLinkSubordinateSubscriberLatencyTxNOK() ;
        public SampleStatistics getLinkSubordinateSubscriberLatencyRxNOK() ;
        public void sampleLinkSubordinateSubscriberLatencyTxOK(long l) ;
        public void sampleLinkSubordinateSubscriberLatencyRxOK(long l) ;
        public void sampleLinkSubordinateSubscriberLatencyTxNOK(long l) ;
        public void sampleLinkSubordinateSubscriberLatencyRxNOK(long l) ;
	
        public void incrementUpdatePromotionCountersTxOK(long l) ;
        public void incrementUpdatePromotionCountersRxOK(long l) ;
        public void incrementUpdatePromotionCountersTxNOK(long l) ;
        public void incrementUpdatePromotionCountersRxNOK(long l) ;
        public long getUpdatePromotionCountersTxOK() ;
        public long getUpdatePromotionCountersRxOK() ;
        public long getUpdatePromotionCountersTxNOK() ;
        public long getUpdatePromotionCountersRxNOK() ;
        public SampleStatistics getUpdatePromotionCountersLatencyTxOK() ;
        public SampleStatistics getUpdatePromotionCountersLatencyRxOK() ;
        public SampleStatistics getUpdatePromotionCountersLatencyTxNOK() ;
        public SampleStatistics getUpdatePromotionCountersLatencyRxNOK() ;
        public void sampleUpdatePromotionCountersLatencyTxOK(long l) ;
        public void sampleUpdatePromotionCountersLatencyRxOK(long l) ;
        public void sampleUpdatePromotionCountersLatencyTxNOK(long l) ;
        public void sampleUpdatePromotionCountersLatencyRxNOK(long l) ;
	
        public void incrementGetPromotionCountersTxOK(long l) ;
        public void incrementGetPromotionCountersRxOK(long l) ;
        public void incrementGetPromotionCountersTxNOK(long l) ;
        public void incrementGetPromotionCountersRxNOK(long l) ;
        public long getGetPromotionCountersTxOK() ;
        public long getGetPromotionCountersRxOK() ;
        public long getGetPromotionCountersTxNOK() ;
        public long getGetPromotionCountersRxNOK() ;
        public SampleStatistics getGetPromotionCountersLatencyTxOK() ;
        public SampleStatistics getGetPromotionCountersLatencyRxOK() ;
        public SampleStatistics getGetPromotionCountersLatencyTxNOK() ;
        public SampleStatistics getGetPromotionCountersLatencyRxNOK() ;
        public void sampleGetPromotionCountersLatencyTxOK(long l) ;
        public void sampleGetPromotionCountersLatencyRxOK(long l) ;
        public void sampleGetPromotionCountersLatencyTxNOK(long l) ;
        public void sampleGetPromotionCountersLatencyRxNOK(long l) ;
	
        public void incrementAccountFlagsTxOK(long l) ;
        public void incrementAccountFlagsRxOK(long l) ;
        public void incrementAccountFlagsTxNOK(long l) ;
        public void incrementAccountFlagsRxNOK(long l) ;
        public long getAccountFlagsTxOK() ;
        public long getAccountFlagsRxOK() ;
        public long getAccountFlagsTxNOK() ;
        public long getAccountFlagsRxNOK() ;
        public SampleStatistics getAccountFlagsLatencyTxOK() ;
        public SampleStatistics getAccountFlagsLatencyRxOK() ;
        public SampleStatistics getAccountFlagsLatencyTxNOK() ;
        public SampleStatistics getAccountFlagsLatencyRxNOK() ;
        public void sampleAccountFlagsLatencyTxOK(long l) ;
        public void sampleAccountFlagsLatencyRxOK(long l) ;
        public void sampleAccountFlagsLatencyTxNOK(long l) ;
        public void sampleAccountFlagsLatencyRxNOK(long l) ;
	
        public void incrementCommunityIdListTxOK(long l) ;
        public void incrementCommunityIdListRxOK(long l) ;
        public void incrementCommunityIdListTxNOK(long l) ;
        public void incrementCommunityIdListRxNOK(long l) ;
        public long getCommunityIdListTxOK() ;
        public long getCommunityIdListRxOK() ;
        public long getCommunityIdListTxNOK() ;
        public long getCommunityIdListRxNOK() ;
        public SampleStatistics getCommunityIdListLatencyTxOK() ;
        public SampleStatistics getCommunityIdListLatencyRxOK() ;
        public SampleStatistics getCommunityIdListLatencyTxNOK() ;
        public SampleStatistics getCommunityIdListLatencyRxNOK() ;
        public void sampleCommunityIdListLatencyTxOK(long l) ;
        public void sampleCommunityIdListLatencyRxOK(long l) ;
        public void sampleCommunityIdListLatencyTxNOK(long l) ;
        public void sampleCommunityIdListLatencyRxNOK(long l) ;
	
        public void incrementCommunityInformationCurrentTxOK(long l) ;
        public void incrementCommunityInformationCurrentRxOK(long l) ;
        public void incrementCommunityInformationCurrentTxNOK(long l) ;
        public void incrementCommunityInformationCurrentRxNOK(long l) ;
        public long getCommunityInformationCurrentTxOK() ;
        public long getCommunityInformationCurrentRxOK() ;
        public long getCommunityInformationCurrentTxNOK() ;
        public long getCommunityInformationCurrentRxNOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyTxOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyRxOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyTxNOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyRxNOK() ;
        public void sampleCommunityInformationCurrentLatencyTxOK(long l) ;
        public void sampleCommunityInformationCurrentLatencyRxOK(long l) ;
        public void sampleCommunityInformationCurrentLatencyTxNOK(long l) ;
        public void sampleCommunityInformationCurrentLatencyRxNOK(long l) ;
	
        public void incrementCommunityInformationNewTxOK(long l) ;
        public void incrementCommunityInformationNewRxOK(long l) ;
        public void incrementCommunityInformationNewTxNOK(long l) ;
        public void incrementCommunityInformationNewRxNOK(long l) ;
        public long getCommunityInformationNewTxOK() ;
        public long getCommunityInformationNewRxOK() ;
        public long getCommunityInformationNewTxNOK() ;
        public long getCommunityInformationNewRxNOK() ;
        public SampleStatistics getCommunityInformationNewLatencyTxOK() ;
        public SampleStatistics getCommunityInformationNewLatencyRxOK() ;
        public SampleStatistics getCommunityInformationNewLatencyTxNOK() ;
        public SampleStatistics getCommunityInformationNewLatencyRxNOK() ;
        public void sampleCommunityInformationNewLatencyTxOK(long l) ;
        public void sampleCommunityInformationNewLatencyRxOK(long l) ;
        public void sampleCommunityInformationNewLatencyTxNOK(long l) ;
        public void sampleCommunityInformationNewLatencyRxNOK(long l) ;
	
        public void incrementDedicatedAccountInformationTxOK(long l) ;
        public void incrementDedicatedAccountInformationRxOK(long l) ;
        public void incrementDedicatedAccountInformationTxNOK(long l) ;
        public void incrementDedicatedAccountInformationRxNOK(long l) ;
        public long getDedicatedAccountInformationTxOK() ;
        public long getDedicatedAccountInformationRxOK() ;
        public long getDedicatedAccountInformationTxNOK() ;
        public long getDedicatedAccountInformationRxNOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyTxOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyRxOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyTxNOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyRxNOK() ;
        public void sampleDedicatedAccountInformationLatencyTxOK(long l) ;
        public void sampleDedicatedAccountInformationLatencyRxOK(long l) ;
        public void sampleDedicatedAccountInformationLatencyTxNOK(long l) ;
        public void sampleDedicatedAccountInformationLatencyRxNOK(long l) ;
	
        public void incrementServiceOfferingsTxOK(long l) ;
        public void incrementServiceOfferingsRxOK(long l) ;
        public void incrementServiceOfferingsTxNOK(long l) ;
        public void incrementServiceOfferingsRxNOK(long l) ;
        public long getServiceOfferingsTxOK() ;
        public long getServiceOfferingsRxOK() ;
        public long getServiceOfferingsTxNOK() ;
        public long getServiceOfferingsRxNOK() ;
        public SampleStatistics getServiceOfferingsLatencyTxOK() ;
        public SampleStatistics getServiceOfferingsLatencyRxOK() ;
        public SampleStatistics getServiceOfferingsLatencyTxNOK() ;
        public SampleStatistics getServiceOfferingsLatencyRxNOK() ;
        public void sampleServiceOfferingsLatencyTxOK(long l) ;
        public void sampleServiceOfferingsLatencyRxOK(long l) ;
        public void sampleServiceOfferingsLatencyTxNOK(long l) ;
        public void sampleServiceOfferingsLatencyRxNOK(long l) ;
	
        }
