//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 04:24:15 PM EST 
//


package com.mofokom.j4mlp.element;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mofokom.j4mlp.element package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Edition_QNAME = new QName("", "edition");
    private final static QName _Cellid_QNAME = new QName("", "cellid");
    private final static QName _Mcc_QNAME = new QName("", "mcc");
    private final static QName _LlAcc_QNAME = new QName("", "ll_acc");
    private final static QName _InnerBoundaryIs_QNAME = new QName("", "innerBoundaryIs");
    private final static QName _Lmsi_QNAME = new QName("", "lmsi");
    private final static QName _Codeword_QNAME = new QName("", "codeword");
    private final static QName _Vlrno_QNAME = new QName("", "vlrno");
    private final static QName _InRadius_QNAME = new QName("", "inRadius");
    private final static QName _Ta_QNAME = new QName("", "ta");
    private final static QName _AddInfo_QNAME = new QName("", "add_info");
    private final static QName _SemiMajor_QNAME = new QName("", "semiMajor");
    private final static QName _HorAcc_QNAME = new QName("", "hor_acc");
    private final static QName _CodeSpace_QNAME = new QName("", "codeSpace");
    private final static QName _OuterBoundaryIs_QNAME = new QName("", "outerBoundaryIs");
    private final static QName _MaxLocAge_QNAME = new QName("", "max_loc_age");
    private final static QName _Code_QNAME = new QName("", "code");
    private final static QName _LevConf_QNAME = new QName("", "lev_conf");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _OutRadius_QNAME = new QName("", "outRadius");
    private final static QName _Ndc_QNAME = new QName("", "ndc");
    private final static QName _AltAcc_QNAME = new QName("", "alt_acc");
    private final static QName _Radius_QNAME = new QName("", "radius");
    private final static QName _Cc_QNAME = new QName("", "cc");
    private final static QName _GeoInfo_QNAME = new QName("", "geo_info");
    private final static QName _Interval_QNAME = new QName("", "interval");
    private final static QName _Direction_QNAME = new QName("", "direction");
    private final static QName _RespTimer_QNAME = new QName("", "resp_timer");
    private final static QName _AngularUnit_QNAME = new QName("", "angularUnit");
    private final static QName _Lac_QNAME = new QName("", "lac");
    private final static QName _Serviceid_QNAME = new QName("", "serviceid");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _StopAngle_QNAME = new QName("", "stopAngle");
    private final static QName _Alt_QNAME = new QName("", "alt");
    private final static QName _ReqId_QNAME = new QName("", "req_id");
    private final static QName _Mnc_QNAME = new QName("", "mnc");
    private final static QName _Y_QNAME = new QName("", "Y");
    private final static QName _X_QNAME = new QName("", "X");
    private final static QName _SemiMinor_QNAME = new QName("", "semiMinor");
    private final static QName _Z_QNAME = new QName("", "Z");
    private final static QName _Speed_QNAME = new QName("", "speed");
    private final static QName _Sessionid_QNAME = new QName("", "sessionid");
    private final static QName _Vmscno_QNAME = new QName("", "vmscno");
    private final static QName _Angle_QNAME = new QName("", "angle");
    private final static QName _Pwd_QNAME = new QName("", "pwd");
    private final static QName _Nmr_QNAME = new QName("", "nmr");
    private final static QName _TlrrEvent_QNAME = new QName("", "tlrr_event");
    private final static QName _StartAngle_QNAME = new QName("", "startAngle");
    private final static QName _DistanceUnit_QNAME = new QName("", "distanceUnit");
    private final static QName _CoordinateReferenceSystem_QNAME = new QName("", "CoordinateReferenceSystem");
    private final static QName _TimeRemaining_QNAME = new QName("", "time_remaining");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mofokom.j4mlp.element
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocType }
     * 
     */
    public LocType createLocType() {
        return new LocType();
    }

    /**
     * Create an instance of {@link MultiLineString }
     * 
     */
    public MultiLineString createMultiLineString() {
        return new MultiLineString();
    }

    /**
     * Create an instance of {@link Slirep }
     * 
     */
    public Slirep createSlirep() {
        return new Slirep();
    }

    /**
     * Create an instance of {@link Eqop }
     * 
     */
    public Eqop createEqop() {
        return new Eqop();
    }

    /**
     * Create an instance of {@link Slrep }
     * 
     */
    public Slrep createSlrep() {
        return new Slrep();
    }

    /**
     * Create an instance of {@link StopMsid }
     * 
     */
    public StopMsid createStopMsid() {
        return new StopMsid();
    }

    /**
     * Create an instance of {@link LineString }
     * 
     */
    public LineString createLineString() {
        return new LineString();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link Pd }
     * 
     */
    public Pd createPd() {
        return new Pd();
    }

    /**
     * Create an instance of {@link CircularArea }
     * 
     */
    public CircularArea createCircularArea() {
        return new CircularArea();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link CoordinateReferenceSystem }
     * 
     */
    public CoordinateReferenceSystem createCoordinateReferenceSystem() {
        return new CoordinateReferenceSystem();
    }

    /**
     * Create an instance of {@link Box }
     * 
     */
    public Box createBox() {
        return new Box();
    }

    /**
     * Create an instance of {@link EmeLia }
     * 
     */
    public EmeLia createEmeLia() {
        return new EmeLia();
    }

    /**
     * Create an instance of {@link Tlrr }
     * 
     */
    public Tlrr createTlrr() {
        return new Tlrr();
    }

    /**
     * Create an instance of {@link Vmscid }
     * 
     */
    public Vmscid createVmscid() {
        return new Vmscid();
    }

    /**
     * Create an instance of {@link Requestmode }
     * 
     */
    public Requestmode createRequestmode() {
        return new Requestmode();
    }

    /**
     * Create an instance of {@link Polygon }
     * 
     */
    public Polygon createPolygon() {
        return new Polygon();
    }

    /**
     * Create an instance of {@link StopTime }
     * 
     */
    public StopTime createStopTime() {
        return new StopTime();
    }

    /**
     * Create an instance of {@link Esrd }
     * 
     */
    public Esrd createEsrd() {
        return new Esrd();
    }

    /**
     * Create an instance of {@link MsAction }
     * 
     */
    public MsAction createMsAction() {
        return new MsAction();
    }

    /**
     * Create an instance of {@link GsmNetParam }
     * 
     */
    public GsmNetParam createGsmNetParam() {
        return new GsmNetParam();
    }

    /**
     * Create an instance of {@link Esrk }
     * 
     */
    public Esrk createEsrk() {
        return new Esrk();
    }

    /**
     * Create an instance of {@link Requestor }
     * 
     */
    public Requestor createRequestor() {
        return new Requestor();
    }

    /**
     * Create an instance of {@link Emerep }
     * 
     */
    public Emerep createEmerep() {
        return new Emerep();
    }

    /**
     * Create an instance of {@link RespReq }
     * 
     */
    public RespReq createRespReq() {
        return new RespReq();
    }

    /**
     * Create an instance of {@link Msids }
     * 
     */
    public Msids createMsids() {
        return new Msids();
    }

    /**
     * Create an instance of {@link EmeLir }
     * 
     */
    public EmeLir createEmeLir() {
        return new EmeLir();
    }

    /**
     * Create an instance of {@link Tlra }
     * 
     */
    public Tlra createTlra() {
        return new Tlra();
    }

    /**
     * Create an instance of {@link LinearRing }
     * 
     */
    public LinearRing createLinearRing() {
        return new LinearRing();
    }

    /**
     * Create an instance of {@link Gem }
     * 
     */
    public Gem createGem() {
        return new Gem();
    }

    /**
     * Create an instance of {@link EmePos }
     * 
     */
    public EmePos createEmePos() {
        return new EmePos();
    }

    /**
     * Create an instance of {@link Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link CircularArcArea }
     * 
     */
    public CircularArcArea createCircularArcArea() {
        return new CircularArcArea();
    }

    /**
     * Create an instance of {@link Slir }
     * 
     */
    public Slir createSlir() {
        return new Slir();
    }

    /**
     * Create an instance of {@link MultiPoint }
     * 
     */
    public MultiPoint createMultiPoint() {
        return new MultiPoint();
    }

    /**
     * Create an instance of {@link Slia }
     * 
     */
    public Slia createSlia() {
        return new Slia();
    }

    /**
     * Create an instance of {@link EmeEvent }
     * 
     */
    public EmeEvent createEmeEvent() {
        return new EmeEvent();
    }

    /**
     * Create an instance of {@link Qop }
     * 
     */
    public Qop createQop() {
        return new Qop();
    }

    /**
     * Create an instance of {@link StartTime }
     * 
     */
    public StartTime createStartTime() {
        return new StartTime();
    }

    /**
     * Create an instance of {@link TrlPos }
     * 
     */
    public TrlPos createTrlPos() {
        return new TrlPos();
    }

    /**
     * Create an instance of {@link Cgi }
     * 
     */
    public Cgi createCgi() {
        return new Cgi();
    }

    /**
     * Create an instance of {@link Tlrsa }
     * 
     */
    public Tlrsa createTlrsa() {
        return new Tlrsa();
    }

    /**
     * Create an instance of {@link Msid }
     * 
     */
    public Msid createMsid() {
        return new Msid();
    }

    /**
     * Create an instance of {@link GeometryCollection }
     * 
     */
    public GeometryCollection createGeometryCollection() {
        return new GeometryCollection();
    }

    /**
     * Create an instance of {@link Neid }
     * 
     */
    public Neid createNeid() {
        return new Neid();
    }

    /**
     * Create an instance of {@link Pushaddr }
     * 
     */
    public Pushaddr createPushaddr() {
        return new Pushaddr();
    }

    /**
     * Create an instance of {@link Subclient }
     * 
     */
    public Subclient createSubclient() {
        return new Subclient();
    }

    /**
     * Create an instance of {@link Vlrid }
     * 
     */
    public Vlrid createVlrid() {
        return new Vlrid();
    }

    /**
     * Create an instance of {@link Poserr }
     * 
     */
    public Poserr createPoserr() {
        return new Poserr();
    }

    /**
     * Create an instance of {@link Tlrsr }
     * 
     */
    public Tlrsr createTlrsr() {
        return new Tlrsr();
    }

    /**
     * Create an instance of {@link MsidRange }
     * 
     */
    public MsidRange createMsidRange() {
        return new MsidRange();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Prio }
     * 
     */
    public Prio createPrio() {
        return new Prio();
    }

    /**
     * Create an instance of {@link StartMsid }
     * 
     */
    public StartMsid createStartMsid() {
        return new StartMsid();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link EllipticalArea }
     * 
     */
    public EllipticalArea createEllipticalArea() {
        return new EllipticalArea();
    }

    /**
     * Create an instance of {@link MultiPolygon }
     * 
     */
    public MultiPolygon createMultiPolygon() {
        return new MultiPolygon();
    }

    /**
     * Create an instance of {@link Coord }
     * 
     */
    public Coord createCoord() {
        return new Coord();
    }

    /**
     * Create an instance of {@link Tlrep }
     * 
     */
    public Tlrep createTlrep() {
        return new Tlrep();
    }

    /**
     * Create an instance of {@link Shape }
     * 
     */
    public Shape createShape() {
        return new Shape();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "edition")
    public JAXBElement<String> createEdition(String value) {
        return new JAXBElement<String>(_Edition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cellid")
    public JAXBElement<String> createCellid(String value) {
        return new JAXBElement<String>(_Cellid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mcc")
    public JAXBElement<String> createMcc(String value) {
        return new JAXBElement<String>(_Mcc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ll_acc")
    public JAXBElement<String> createLlAcc(String value) {
        return new JAXBElement<String>(_LlAcc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinearRing }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "innerBoundaryIs")
    public JAXBElement<LinearRing> createInnerBoundaryIs(LinearRing value) {
        return new JAXBElement<LinearRing>(_InnerBoundaryIs_QNAME, LinearRing.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lmsi")
    public JAXBElement<String> createLmsi(String value) {
        return new JAXBElement<String>(_Lmsi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codeword")
    public JAXBElement<String> createCodeword(String value) {
        return new JAXBElement<String>(_Codeword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vlrno")
    public JAXBElement<String> createVlrno(String value) {
        return new JAXBElement<String>(_Vlrno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inRadius")
    public JAXBElement<String> createInRadius(String value) {
        return new JAXBElement<String>(_InRadius_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ta")
    public JAXBElement<String> createTa(String value) {
        return new JAXBElement<String>(_Ta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "add_info")
    public JAXBElement<String> createAddInfo(String value) {
        return new JAXBElement<String>(_AddInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "semiMajor")
    public JAXBElement<String> createSemiMajor(String value) {
        return new JAXBElement<String>(_SemiMajor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hor_acc")
    public JAXBElement<String> createHorAcc(String value) {
        return new JAXBElement<String>(_HorAcc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codeSpace")
    public JAXBElement<String> createCodeSpace(String value) {
        return new JAXBElement<String>(_CodeSpace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinearRing }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outerBoundaryIs")
    public JAXBElement<LinearRing> createOuterBoundaryIs(LinearRing value) {
        return new JAXBElement<LinearRing>(_OuterBoundaryIs_QNAME, LinearRing.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "max_loc_age")
    public JAXBElement<String> createMaxLocAge(String value) {
        return new JAXBElement<String>(_MaxLocAge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lev_conf")
    public JAXBElement<String> createLevConf(String value) {
        return new JAXBElement<String>(_LevConf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outRadius")
    public JAXBElement<String> createOutRadius(String value) {
        return new JAXBElement<String>(_OutRadius_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ndc")
    public JAXBElement<String> createNdc(String value) {
        return new JAXBElement<String>(_Ndc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "alt_acc")
    public JAXBElement<String> createAltAcc(String value) {
        return new JAXBElement<String>(_AltAcc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "radius")
    public JAXBElement<String> createRadius(String value) {
        return new JAXBElement<String>(_Radius_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cc")
    public JAXBElement<String> createCc(String value) {
        return new JAXBElement<String>(_Cc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoordinateReferenceSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geo_info")
    public JAXBElement<CoordinateReferenceSystem> createGeoInfo(CoordinateReferenceSystem value) {
        return new JAXBElement<CoordinateReferenceSystem>(_GeoInfo_QNAME, CoordinateReferenceSystem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "interval")
    public JAXBElement<String> createInterval(String value) {
        return new JAXBElement<String>(_Interval_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "direction")
    public JAXBElement<String> createDirection(String value) {
        return new JAXBElement<String>(_Direction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resp_timer")
    public JAXBElement<String> createRespTimer(String value) {
        return new JAXBElement<String>(_RespTimer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angularUnit")
    public JAXBElement<String> createAngularUnit(String value) {
        return new JAXBElement<String>(_AngularUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lac")
    public JAXBElement<String> createLac(String value) {
        return new JAXBElement<String>(_Lac_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceid")
    public JAXBElement<String> createServiceid(String value) {
        return new JAXBElement<String>(_Serviceid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stopAngle")
    public JAXBElement<String> createStopAngle(String value) {
        return new JAXBElement<String>(_StopAngle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "alt")
    public JAXBElement<String> createAlt(String value) {
        return new JAXBElement<String>(_Alt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "req_id")
    public JAXBElement<String> createReqId(String value) {
        return new JAXBElement<String>(_ReqId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mnc")
    public JAXBElement<String> createMnc(String value) {
        return new JAXBElement<String>(_Mnc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Y")
    public JAXBElement<String> createY(String value) {
        return new JAXBElement<String>(_Y_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "X")
    public JAXBElement<String> createX(String value) {
        return new JAXBElement<String>(_X_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "semiMinor")
    public JAXBElement<String> createSemiMinor(String value) {
        return new JAXBElement<String>(_SemiMinor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Z")
    public JAXBElement<String> createZ(String value) {
        return new JAXBElement<String>(_Z_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "speed")
    public JAXBElement<String> createSpeed(String value) {
        return new JAXBElement<String>(_Speed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sessionid")
    public JAXBElement<String> createSessionid(String value) {
        return new JAXBElement<String>(_Sessionid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vmscno")
    public JAXBElement<String> createVmscno(String value) {
        return new JAXBElement<String>(_Vmscno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angle")
    public JAXBElement<String> createAngle(String value) {
        return new JAXBElement<String>(_Angle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pwd")
    public JAXBElement<String> createPwd(String value) {
        return new JAXBElement<String>(_Pwd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nmr")
    public JAXBElement<String> createNmr(String value) {
        return new JAXBElement<String>(_Nmr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MsAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tlrr_event")
    public JAXBElement<MsAction> createTlrrEvent(MsAction value) {
        return new JAXBElement<MsAction>(_TlrrEvent_QNAME, MsAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "startAngle")
    public JAXBElement<String> createStartAngle(String value) {
        return new JAXBElement<String>(_StartAngle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "distanceUnit")
    public JAXBElement<String> createDistanceUnit(String value) {
        return new JAXBElement<String>(_DistanceUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Identifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CoordinateReferenceSystem")
    public JAXBElement<Identifier> createCoordinateReferenceSystem(Identifier value) {
        return new JAXBElement<Identifier>(_CoordinateReferenceSystem_QNAME, Identifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time_remaining")
    public JAXBElement<String> createTimeRemaining(String value) {
        return new JAXBElement<String>(_TimeRemaining_QNAME, String.class, null, value);
    }

}
