//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 04:24:15 PM EST 
//


package com.mofokom.j4mlp.element;

import java.io.Serializable;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}Point"/>
 *         &lt;element ref="{}LineString"/>
 *         &lt;element ref="{}Polygon"/>
 *         &lt;element ref="{}Box"/>
 *         &lt;element ref="{}CircularArea"/>
 *         &lt;element ref="{}CircularArcArea"/>
 *         &lt;element ref="{}EllipticalArea"/>
 *         &lt;element ref="{}GeometryCollection"/>
 *         &lt;element ref="{}MultiLineString"/>
 *         &lt;element ref="{}MultiPoint"/>
 *         &lt;element ref="{}MultiPolygon"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "point",
    "lineString",
    "polygon",
    "box",
    "circularArea",
    "circularArcArea",
    "ellipticalArea",
    "geometryCollection",
    "multiLineString",
    "multiPoint",
    "multiPolygon"
})
@XmlRootElement(name = "shape")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
public class Shape
    implements Serializable, Cloneable
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Point")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Point point;
    @XmlElement(name = "LineString")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected LineString lineString;
    @XmlElement(name = "Polygon")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Polygon polygon;
    @XmlElement(name = "Box")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Box box;
    @XmlElement(name = "CircularArea")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected CircularArea circularArea;
    @XmlElement(name = "CircularArcArea")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected CircularArcArea circularArcArea;
    @XmlElement(name = "EllipticalArea")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected EllipticalArea ellipticalArea;
    @XmlElement(name = "GeometryCollection")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected GeometryCollection geometryCollection;
    @XmlElement(name = "MultiLineString")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected MultiLineString multiLineString;
    @XmlElement(name = "MultiPoint")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected MultiPoint multiPoint;
    @XmlElement(name = "MultiPolygon")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected MultiPolygon multiPolygon;

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Point getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setPoint(Point value) {
        this.point = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetPoint() {
        return (this.point!= null);
    }

    /**
     * Gets the value of the lineString property.
     * 
     * @return
     *     possible object is
     *     {@link LineString }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public LineString getLineString() {
        return lineString;
    }

    /**
     * Sets the value of the lineString property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineString }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setLineString(LineString value) {
        this.lineString = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetLineString() {
        return (this.lineString!= null);
    }

    /**
     * Gets the value of the polygon property.
     * 
     * @return
     *     possible object is
     *     {@link Polygon }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Polygon getPolygon() {
        return polygon;
    }

    /**
     * Sets the value of the polygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Polygon }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setPolygon(Polygon value) {
        this.polygon = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetPolygon() {
        return (this.polygon!= null);
    }

    /**
     * Gets the value of the box property.
     * 
     * @return
     *     possible object is
     *     {@link Box }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Box getBox() {
        return box;
    }

    /**
     * Sets the value of the box property.
     * 
     * @param value
     *     allowed object is
     *     {@link Box }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setBox(Box value) {
        this.box = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetBox() {
        return (this.box!= null);
    }

    /**
     * Gets the value of the circularArea property.
     * 
     * @return
     *     possible object is
     *     {@link CircularArea }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public CircularArea getCircularArea() {
        return circularArea;
    }

    /**
     * Sets the value of the circularArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link CircularArea }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setCircularArea(CircularArea value) {
        this.circularArea = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetCircularArea() {
        return (this.circularArea!= null);
    }

    /**
     * Gets the value of the circularArcArea property.
     * 
     * @return
     *     possible object is
     *     {@link CircularArcArea }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public CircularArcArea getCircularArcArea() {
        return circularArcArea;
    }

    /**
     * Sets the value of the circularArcArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link CircularArcArea }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setCircularArcArea(CircularArcArea value) {
        this.circularArcArea = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetCircularArcArea() {
        return (this.circularArcArea!= null);
    }

    /**
     * Gets the value of the ellipticalArea property.
     * 
     * @return
     *     possible object is
     *     {@link EllipticalArea }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public EllipticalArea getEllipticalArea() {
        return ellipticalArea;
    }

    /**
     * Sets the value of the ellipticalArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link EllipticalArea }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setEllipticalArea(EllipticalArea value) {
        this.ellipticalArea = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetEllipticalArea() {
        return (this.ellipticalArea!= null);
    }

    /**
     * Gets the value of the geometryCollection property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryCollection }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public GeometryCollection getGeometryCollection() {
        return geometryCollection;
    }

    /**
     * Sets the value of the geometryCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryCollection }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setGeometryCollection(GeometryCollection value) {
        this.geometryCollection = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetGeometryCollection() {
        return (this.geometryCollection!= null);
    }

    /**
     * Gets the value of the multiLineString property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLineString }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public MultiLineString getMultiLineString() {
        return multiLineString;
    }

    /**
     * Sets the value of the multiLineString property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLineString }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setMultiLineString(MultiLineString value) {
        this.multiLineString = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetMultiLineString() {
        return (this.multiLineString!= null);
    }

    /**
     * Gets the value of the multiPoint property.
     * 
     * @return
     *     possible object is
     *     {@link MultiPoint }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public MultiPoint getMultiPoint() {
        return multiPoint;
    }

    /**
     * Sets the value of the multiPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiPoint }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setMultiPoint(MultiPoint value) {
        this.multiPoint = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetMultiPoint() {
        return (this.multiPoint!= null);
    }

    /**
     * Gets the value of the multiPolygon property.
     * 
     * @return
     *     possible object is
     *     {@link MultiPolygon }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public MultiPolygon getMultiPolygon() {
        return multiPolygon;
    }

    /**
     * Sets the value of the multiPolygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiPolygon }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setMultiPolygon(MultiPolygon value) {
        this.multiPolygon = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetMultiPolygon() {
        return (this.multiPolygon!= null);
    }

    public Object clone()
        throws CloneNotSupportedException
    {
        return super.clone();
    }

    public String toString() {
        StringBuilder buffy;
        buffy = new StringBuilder();
        buffy.append("Shape{");
        buffy.append("point=");
        if (point == null) {
            buffy.append("<null>");
        } else {
            buffy.append(point.toString());
        }
        buffy.append(",");
        buffy.append("lineString=");
        if (lineString == null) {
            buffy.append("<null>");
        } else {
            buffy.append(lineString.toString());
        }
        buffy.append(",");
        buffy.append("polygon=");
        if (polygon == null) {
            buffy.append("<null>");
        } else {
            buffy.append(polygon.toString());
        }
        buffy.append(",");
        buffy.append("box=");
        if (box == null) {
            buffy.append("<null>");
        } else {
            buffy.append(box.toString());
        }
        buffy.append(",");
        buffy.append("circularArea=");
        if (circularArea == null) {
            buffy.append("<null>");
        } else {
            buffy.append(circularArea.toString());
        }
        buffy.append(",");
        buffy.append("circularArcArea=");
        if (circularArcArea == null) {
            buffy.append("<null>");
        } else {
            buffy.append(circularArcArea.toString());
        }
        buffy.append(",");
        buffy.append("ellipticalArea=");
        if (ellipticalArea == null) {
            buffy.append("<null>");
        } else {
            buffy.append(ellipticalArea.toString());
        }
        buffy.append(",");
        buffy.append("geometryCollection=");
        if (geometryCollection == null) {
            buffy.append("<null>");
        } else {
            buffy.append(geometryCollection.toString());
        }
        buffy.append(",");
        buffy.append("multiLineString=");
        if (multiLineString == null) {
            buffy.append("<null>");
        } else {
            buffy.append(multiLineString.toString());
        }
        buffy.append(",");
        buffy.append("multiPoint=");
        if (multiPoint == null) {
            buffy.append("<null>");
        } else {
            buffy.append(multiPoint.toString());
        }
        buffy.append(",");
        buffy.append("multiPolygon=");
        if (multiPolygon == null) {
            buffy.append("<null>");
        } else {
            buffy.append(multiPolygon.toString());
        }
        buffy.append(",");
        buffy.append("}");
        return buffy.toString();
    }

}
