//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 04:24:15 PM EST 
//


package com.mofokom.j4mlp.element;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}msids"/>
 *           &lt;sequence maxOccurs="unbounded">
 *             &lt;element ref="{}msid"/>
 *             &lt;element ref="{}codeword" minOccurs="0"/>
 *             &lt;element ref="{}gsm_net_param"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}eqop" minOccurs="0"/>
 *         &lt;element ref="{}geo_info" minOccurs="0"/>
 *         &lt;element ref="{}loc_type" minOccurs="0"/>
 *         &lt;element ref="{}prio" minOccurs="0"/>
 *         &lt;element ref="{}pushaddr" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ver" default="3.0.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="3.0.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="res_type" default="SYNC">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="SYNC"/>
 *             &lt;enumeration value="ASYNC"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msids",
    "msidAndCodewordAndGsmNetParam",
    "eqop",
    "geoInfo",
    "locType",
    "prio",
    "pushaddr"
})
@XmlRootElement(name = "slir")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
public class Slir
    implements Serializable, Cloneable
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    private final static long serialVersionUID = 1L;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Msids msids;
    @XmlElements({
        @XmlElement(name = "msid", type = Msid.class),
        @XmlElement(name = "gsm_net_param", type = GsmNetParam.class),
        @XmlElement(name = "codeword", type = String.class)
    })
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected List<Object> msidAndCodewordAndGsmNetParam;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Eqop eqop;
    @XmlElement(name = "geo_info")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected CoordinateReferenceSystem geoInfo;
    @XmlElement(name = "loc_type")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected LocType locType;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Prio prio;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected Pushaddr pushaddr;
    @XmlAttribute
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected String ver;
    @XmlAttribute(name = "res_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    protected String resType;

    /**
     * Gets the value of the msids property.
     * 
     * @return
     *     possible object is
     *     {@link Msids }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Msids getMsids() {
        return msids;
    }

    /**
     * Sets the value of the msids property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msids }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setMsids(Msids value) {
        this.msids = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetMsids() {
        return (this.msids!= null);
    }

    /**
     * Gets the value of the msidAndCodewordAndGsmNetParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msidAndCodewordAndGsmNetParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsidAndCodewordAndGsmNetParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Msid }
     * {@link GsmNetParam }
     * {@link String }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public List<Object> getMsidAndCodewordAndGsmNetParam() {
        if (msidAndCodewordAndGsmNetParam == null) {
            msidAndCodewordAndGsmNetParam = new ArrayList<Object>();
        }
        return this.msidAndCodewordAndGsmNetParam;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetMsidAndCodewordAndGsmNetParam() {
        return ((this.msidAndCodewordAndGsmNetParam!= null)&&(!this.msidAndCodewordAndGsmNetParam.isEmpty()));
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void unsetMsidAndCodewordAndGsmNetParam() {
        this.msidAndCodewordAndGsmNetParam = null;
    }

    /**
     * Gets the value of the eqop property.
     * 
     * @return
     *     possible object is
     *     {@link Eqop }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Eqop getEqop() {
        return eqop;
    }

    /**
     * Sets the value of the eqop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eqop }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setEqop(Eqop value) {
        this.eqop = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetEqop() {
        return (this.eqop!= null);
    }

    /**
     * Gets the value of the geoInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateReferenceSystem }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public CoordinateReferenceSystem getGeoInfo() {
        return geoInfo;
    }

    /**
     * Sets the value of the geoInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateReferenceSystem }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setGeoInfo(CoordinateReferenceSystem value) {
        this.geoInfo = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetGeoInfo() {
        return (this.geoInfo!= null);
    }

    /**
     * Gets the value of the locType property.
     * 
     * @return
     *     possible object is
     *     {@link LocType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public LocType getLocType() {
        return locType;
    }

    /**
     * Sets the value of the locType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setLocType(LocType value) {
        this.locType = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetLocType() {
        return (this.locType!= null);
    }

    /**
     * Gets the value of the prio property.
     * 
     * @return
     *     possible object is
     *     {@link Prio }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Prio getPrio() {
        return prio;
    }

    /**
     * Sets the value of the prio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prio }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setPrio(Prio value) {
        this.prio = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetPrio() {
        return (this.prio!= null);
    }

    /**
     * Gets the value of the pushaddr property.
     * 
     * @return
     *     possible object is
     *     {@link Pushaddr }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public Pushaddr getPushaddr() {
        return pushaddr;
    }

    /**
     * Sets the value of the pushaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pushaddr }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setPushaddr(Pushaddr value) {
        this.pushaddr = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetPushaddr() {
        return (this.pushaddr!= null);
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public String getVer() {
        if (ver == null) {
            return "3.0.0";
        } else {
            return ver;
        }
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setVer(String value) {
        this.ver = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetVer() {
        return (this.ver!= null);
    }

    /**
     * Gets the value of the resType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public String getResType() {
        if (resType == null) {
            return "SYNC";
        } else {
            return resType;
        }
    }

    /**
     * Sets the value of the resType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public void setResType(String value) {
        this.resType = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-03-27T04:24:15+11:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-792")
    public boolean isSetResType() {
        return (this.resType!= null);
    }

    public Object clone()
        throws CloneNotSupportedException
    {
        return super.clone();
    }

    public String toString() {
        StringBuilder buffy;
        buffy = new StringBuilder();
        buffy.append("Slir{");
        buffy.append("msids=");
        if (msids == null) {
            buffy.append("<null>");
        } else {
            buffy.append(msids.toString());
        }
        buffy.append(",");
        buffy.append("msidAndCodewordAndGsmNetParam=");
        if (msidAndCodewordAndGsmNetParam == null) {
            buffy.append("<null>");
        } else {
            buffy.append("[");
            for (Object e: msidAndCodewordAndGsmNetParam) {
                if (e instanceof JAXBElement) {
                    buffy.append((((JAXBElement) e).getValue()+","));
                } else {
                    buffy.append((e.toString()+","));
                }
            }
            buffy.append("]");
        }
        buffy.append(",");
        buffy.append("eqop=");
        if (eqop == null) {
            buffy.append("<null>");
        } else {
            buffy.append(eqop.toString());
        }
        buffy.append(",");
        buffy.append("geoInfo=");
        if (geoInfo == null) {
            buffy.append("<null>");
        } else {
            buffy.append(geoInfo.toString());
        }
        buffy.append(",");
        buffy.append("locType=");
        if (locType == null) {
            buffy.append("<null>");
        } else {
            buffy.append(locType.toString());
        }
        buffy.append(",");
        buffy.append("prio=");
        if (prio == null) {
            buffy.append("<null>");
        } else {
            buffy.append(prio.toString());
        }
        buffy.append(",");
        buffy.append("pushaddr=");
        if (pushaddr == null) {
            buffy.append("<null>");
        } else {
            buffy.append(pushaddr.toString());
        }
        buffy.append(",");
        buffy.append("ver=");
        if (ver == null) {
            buffy.append("<null>");
        } else {
            buffy.append(ver.toString());
        }
        buffy.append(",");
        buffy.append("resType=");
        if (resType == null) {
            buffy.append("<null>");
        } else {
            buffy.append(resType.toString());
        }
        buffy.append(",");
        buffy.append("}");
        return buffy.toString();
    }

}
