	
          package mofokom.ccn.air.ucip.resource;
          import javax.annotation.Generated;
          import javax.slee.usage.SampleStatistics;
          import mofokom.ccn.resource.ResourceAdaptorUsageParameters;
          @Generated(value={})
          public interface UCIPResourceAdaptorUsageParameters extends ResourceAdaptorUsageParameters {
        public void incrementTxOK(long l) ;
        public void incrementRxOK(long l) ;
        public void incrementTxNOK(long l) ;
        public void incrementRxNOK(long l) ;
        public long getTxOK() ;
        public long getRxOK() ;
        public long getTxNOK() ;
        public long getRxNOK() ;
        public SampleStatistics getLatencyTxOK() ;
        public SampleStatistics getLatencyRxOK() ;
        public SampleStatistics getLatencyTxNOK() ;
        public SampleStatistics getLatencyRxNOK() ;
        public void sampleLatencyTxOK(long l) ;
        public void sampleLatencyRxOK(long l) ;
        public void sampleLatencyTxNOK(long l) ;
        public void sampleLatencyRxNOK(long l) ;
        public void incrementFaultTxOK(long l) ;
        public void incrementFaultRxOK(long l) ;
        public void incrementFaultTxNOK(long l) ;
        public void incrementFaultRxNOK(long l) ;
        public long getFaultTxOK() ;
        public long getFaultRxOK() ;
        public long getFaultTxNOK() ;
        public long getFaultRxNOK() ;
        public SampleStatistics getFaultLatencyTxOK() ;
        public SampleStatistics getFaultLatencyRxOK() ;
        public SampleStatistics getFaultLatencyTxNOK() ;
        public SampleStatistics getFaultLatencyRxNOK() ;
        public void sampleFaultLatencyTxOK(long l) ;
        public void sampleFaultLatencyRxOK(long l) ;
        public void sampleFaultLatencyTxNOK(long l) ;
        public void sampleFaultLatencyRxNOK(long l) ;
	
        public void incrementGetAccumulatorsTxOK(long l) ;
        public void incrementGetAccumulatorsRxOK(long l) ;
        public void incrementGetAccumulatorsTxNOK(long l) ;
        public void incrementGetAccumulatorsRxNOK(long l) ;
        public long getGetAccumulatorsTxOK() ;
        public long getGetAccumulatorsRxOK() ;
        public long getGetAccumulatorsTxNOK() ;
        public long getGetAccumulatorsRxNOK() ;
        public SampleStatistics getGetAccumulatorsLatencyTxOK() ;
        public SampleStatistics getGetAccumulatorsLatencyRxOK() ;
        public SampleStatistics getGetAccumulatorsLatencyTxNOK() ;
        public SampleStatistics getGetAccumulatorsLatencyRxNOK() ;
        public void sampleGetAccumulatorsLatencyTxOK(long l) ;
        public void sampleGetAccumulatorsLatencyRxOK(long l) ;
        public void sampleGetAccumulatorsLatencyTxNOK(long l) ;
        public void sampleGetAccumulatorsLatencyRxNOK(long l) ;
	
        public void incrementAccumulatorInformationTxOK(long l) ;
        public void incrementAccumulatorInformationRxOK(long l) ;
        public void incrementAccumulatorInformationTxNOK(long l) ;
        public void incrementAccumulatorInformationRxNOK(long l) ;
        public long getAccumulatorInformationTxOK() ;
        public long getAccumulatorInformationRxOK() ;
        public long getAccumulatorInformationTxNOK() ;
        public long getAccumulatorInformationRxNOK() ;
        public SampleStatistics getAccumulatorInformationLatencyTxOK() ;
        public SampleStatistics getAccumulatorInformationLatencyRxOK() ;
        public SampleStatistics getAccumulatorInformationLatencyTxNOK() ;
        public SampleStatistics getAccumulatorInformationLatencyRxNOK() ;
        public void sampleAccumulatorInformationLatencyTxOK(long l) ;
        public void sampleAccumulatorInformationLatencyRxOK(long l) ;
        public void sampleAccumulatorInformationLatencyTxNOK(long l) ;
        public void sampleAccumulatorInformationLatencyRxNOK(long l) ;
	
        public void incrementUpdateBalanceAndDateTxOK(long l) ;
        public void incrementUpdateBalanceAndDateRxOK(long l) ;
        public void incrementUpdateBalanceAndDateTxNOK(long l) ;
        public void incrementUpdateBalanceAndDateRxNOK(long l) ;
        public long getUpdateBalanceAndDateTxOK() ;
        public long getUpdateBalanceAndDateRxOK() ;
        public long getUpdateBalanceAndDateTxNOK() ;
        public long getUpdateBalanceAndDateRxNOK() ;
        public SampleStatistics getUpdateBalanceAndDateLatencyTxOK() ;
        public SampleStatistics getUpdateBalanceAndDateLatencyRxOK() ;
        public SampleStatistics getUpdateBalanceAndDateLatencyTxNOK() ;
        public SampleStatistics getUpdateBalanceAndDateLatencyRxNOK() ;
        public void sampleUpdateBalanceAndDateLatencyTxOK(long l) ;
        public void sampleUpdateBalanceAndDateLatencyRxOK(long l) ;
        public void sampleUpdateBalanceAndDateLatencyTxNOK(long l) ;
        public void sampleUpdateBalanceAndDateLatencyRxNOK(long l) ;
	
        public void incrementDedicatedAccountUpdateInformationTxOK(long l) ;
        public void incrementDedicatedAccountUpdateInformationRxOK(long l) ;
        public void incrementDedicatedAccountUpdateInformationTxNOK(long l) ;
        public void incrementDedicatedAccountUpdateInformationRxNOK(long l) ;
        public long getDedicatedAccountUpdateInformationTxOK() ;
        public long getDedicatedAccountUpdateInformationRxOK() ;
        public long getDedicatedAccountUpdateInformationTxNOK() ;
        public long getDedicatedAccountUpdateInformationRxNOK() ;
        public SampleStatistics getDedicatedAccountUpdateInformationLatencyTxOK() ;
        public SampleStatistics getDedicatedAccountUpdateInformationLatencyRxOK() ;
        public SampleStatistics getDedicatedAccountUpdateInformationLatencyTxNOK() ;
        public SampleStatistics getDedicatedAccountUpdateInformationLatencyRxNOK() ;
        public void sampleDedicatedAccountUpdateInformationLatencyTxOK(long l) ;
        public void sampleDedicatedAccountUpdateInformationLatencyRxOK(long l) ;
        public void sampleDedicatedAccountUpdateInformationLatencyTxNOK(long l) ;
        public void sampleDedicatedAccountUpdateInformationLatencyRxNOK(long l) ;
	
        public void incrementGetBalanceAndDateTxOK(long l) ;
        public void incrementGetBalanceAndDateRxOK(long l) ;
        public void incrementGetBalanceAndDateTxNOK(long l) ;
        public void incrementGetBalanceAndDateRxNOK(long l) ;
        public long getGetBalanceAndDateTxOK() ;
        public long getGetBalanceAndDateRxOK() ;
        public long getGetBalanceAndDateTxNOK() ;
        public long getGetBalanceAndDateRxNOK() ;
        public SampleStatistics getGetBalanceAndDateLatencyTxOK() ;
        public SampleStatistics getGetBalanceAndDateLatencyRxOK() ;
        public SampleStatistics getGetBalanceAndDateLatencyTxNOK() ;
        public SampleStatistics getGetBalanceAndDateLatencyRxNOK() ;
        public void sampleGetBalanceAndDateLatencyTxOK(long l) ;
        public void sampleGetBalanceAndDateLatencyRxOK(long l) ;
        public void sampleGetBalanceAndDateLatencyTxNOK(long l) ;
        public void sampleGetBalanceAndDateLatencyRxNOK(long l) ;
	
        public void incrementGetAccountDetailsTxOK(long l) ;
        public void incrementGetAccountDetailsRxOK(long l) ;
        public void incrementGetAccountDetailsTxNOK(long l) ;
        public void incrementGetAccountDetailsRxNOK(long l) ;
        public long getGetAccountDetailsTxOK() ;
        public long getGetAccountDetailsRxOK() ;
        public long getGetAccountDetailsTxNOK() ;
        public long getGetAccountDetailsRxNOK() ;
        public SampleStatistics getGetAccountDetailsLatencyTxOK() ;
        public SampleStatistics getGetAccountDetailsLatencyRxOK() ;
        public SampleStatistics getGetAccountDetailsLatencyTxNOK() ;
        public SampleStatistics getGetAccountDetailsLatencyRxNOK() ;
        public void sampleGetAccountDetailsLatencyTxOK(long l) ;
        public void sampleGetAccountDetailsLatencyRxOK(long l) ;
        public void sampleGetAccountDetailsLatencyTxNOK(long l) ;
        public void sampleGetAccountDetailsLatencyRxNOK(long l) ;
	
        public void incrementGetAllowedServiceClassesTxOK(long l) ;
        public void incrementGetAllowedServiceClassesRxOK(long l) ;
        public void incrementGetAllowedServiceClassesTxNOK(long l) ;
        public void incrementGetAllowedServiceClassesRxNOK(long l) ;
        public long getGetAllowedServiceClassesTxOK() ;
        public long getGetAllowedServiceClassesRxOK() ;
        public long getGetAllowedServiceClassesTxNOK() ;
        public long getGetAllowedServiceClassesRxNOK() ;
        public SampleStatistics getGetAllowedServiceClassesLatencyTxOK() ;
        public SampleStatistics getGetAllowedServiceClassesLatencyRxOK() ;
        public SampleStatistics getGetAllowedServiceClassesLatencyTxNOK() ;
        public SampleStatistics getGetAllowedServiceClassesLatencyRxNOK() ;
        public void sampleGetAllowedServiceClassesLatencyTxOK(long l) ;
        public void sampleGetAllowedServiceClassesLatencyRxOK(long l) ;
        public void sampleGetAllowedServiceClassesLatencyTxNOK(long l) ;
        public void sampleGetAllowedServiceClassesLatencyRxNOK(long l) ;
	
        public void incrementGetFaFListTxOK(long l) ;
        public void incrementGetFaFListRxOK(long l) ;
        public void incrementGetFaFListTxNOK(long l) ;
        public void incrementGetFaFListRxNOK(long l) ;
        public long getGetFaFListTxOK() ;
        public long getGetFaFListRxOK() ;
        public long getGetFaFListTxNOK() ;
        public long getGetFaFListRxNOK() ;
        public SampleStatistics getGetFaFListLatencyTxOK() ;
        public SampleStatistics getGetFaFListLatencyRxOK() ;
        public SampleStatistics getGetFaFListLatencyTxNOK() ;
        public SampleStatistics getGetFaFListLatencyRxNOK() ;
        public void sampleGetFaFListLatencyTxOK(long l) ;
        public void sampleGetFaFListLatencyRxOK(long l) ;
        public void sampleGetFaFListLatencyTxNOK(long l) ;
        public void sampleGetFaFListLatencyRxNOK(long l) ;
	
        public void incrementGetRefillOptionsTxOK(long l) ;
        public void incrementGetRefillOptionsRxOK(long l) ;
        public void incrementGetRefillOptionsTxNOK(long l) ;
        public void incrementGetRefillOptionsRxNOK(long l) ;
        public long getGetRefillOptionsTxOK() ;
        public long getGetRefillOptionsRxOK() ;
        public long getGetRefillOptionsTxNOK() ;
        public long getGetRefillOptionsRxNOK() ;
        public SampleStatistics getGetRefillOptionsLatencyTxOK() ;
        public SampleStatistics getGetRefillOptionsLatencyRxOK() ;
        public SampleStatistics getGetRefillOptionsLatencyTxNOK() ;
        public SampleStatistics getGetRefillOptionsLatencyRxNOK() ;
        public void sampleGetRefillOptionsLatencyTxOK(long l) ;
        public void sampleGetRefillOptionsLatencyRxOK(long l) ;
        public void sampleGetRefillOptionsLatencyTxNOK(long l) ;
        public void sampleGetRefillOptionsLatencyRxNOK(long l) ;
	
        public void incrementRefillTxOK(long l) ;
        public void incrementRefillRxOK(long l) ;
        public void incrementRefillTxNOK(long l) ;
        public void incrementRefillRxNOK(long l) ;
        public long getRefillTxOK() ;
        public long getRefillRxOK() ;
        public long getRefillTxNOK() ;
        public long getRefillRxNOK() ;
        public SampleStatistics getRefillLatencyTxOK() ;
        public SampleStatistics getRefillLatencyRxOK() ;
        public SampleStatistics getRefillLatencyTxNOK() ;
        public SampleStatistics getRefillLatencyRxNOK() ;
        public void sampleRefillLatencyTxOK(long l) ;
        public void sampleRefillLatencyRxOK(long l) ;
        public void sampleRefillLatencyTxNOK(long l) ;
        public void sampleRefillLatencyRxNOK(long l) ;
	
        public void incrementAccountBeforeRefillTxOK(long l) ;
        public void incrementAccountBeforeRefillRxOK(long l) ;
        public void incrementAccountBeforeRefillTxNOK(long l) ;
        public void incrementAccountBeforeRefillRxNOK(long l) ;
        public long getAccountBeforeRefillTxOK() ;
        public long getAccountBeforeRefillRxOK() ;
        public long getAccountBeforeRefillTxNOK() ;
        public long getAccountBeforeRefillRxNOK() ;
        public SampleStatistics getAccountBeforeRefillLatencyTxOK() ;
        public SampleStatistics getAccountBeforeRefillLatencyRxOK() ;
        public SampleStatistics getAccountBeforeRefillLatencyTxNOK() ;
        public SampleStatistics getAccountBeforeRefillLatencyRxNOK() ;
        public void sampleAccountBeforeRefillLatencyTxOK(long l) ;
        public void sampleAccountBeforeRefillLatencyRxOK(long l) ;
        public void sampleAccountBeforeRefillLatencyTxNOK(long l) ;
        public void sampleAccountBeforeRefillLatencyRxNOK(long l) ;
	
        public void incrementAccountAfterRefillTxOK(long l) ;
        public void incrementAccountAfterRefillRxOK(long l) ;
        public void incrementAccountAfterRefillTxNOK(long l) ;
        public void incrementAccountAfterRefillRxNOK(long l) ;
        public long getAccountAfterRefillTxOK() ;
        public long getAccountAfterRefillRxOK() ;
        public long getAccountAfterRefillTxNOK() ;
        public long getAccountAfterRefillRxNOK() ;
        public SampleStatistics getAccountAfterRefillLatencyTxOK() ;
        public SampleStatistics getAccountAfterRefillLatencyRxOK() ;
        public SampleStatistics getAccountAfterRefillLatencyTxNOK() ;
        public SampleStatistics getAccountAfterRefillLatencyRxNOK() ;
        public void sampleAccountAfterRefillLatencyTxOK(long l) ;
        public void sampleAccountAfterRefillLatencyRxOK(long l) ;
        public void sampleAccountAfterRefillLatencyTxNOK(long l) ;
        public void sampleAccountAfterRefillLatencyRxNOK(long l) ;
	
        public void incrementRefillInformationTxOK(long l) ;
        public void incrementRefillInformationRxOK(long l) ;
        public void incrementRefillInformationTxNOK(long l) ;
        public void incrementRefillInformationRxNOK(long l) ;
        public long getRefillInformationTxOK() ;
        public long getRefillInformationRxOK() ;
        public long getRefillInformationTxNOK() ;
        public long getRefillInformationRxNOK() ;
        public SampleStatistics getRefillInformationLatencyTxOK() ;
        public SampleStatistics getRefillInformationLatencyRxOK() ;
        public SampleStatistics getRefillInformationLatencyTxNOK() ;
        public SampleStatistics getRefillInformationLatencyRxNOK() ;
        public void sampleRefillInformationLatencyTxOK(long l) ;
        public void sampleRefillInformationLatencyRxOK(long l) ;
        public void sampleRefillInformationLatencyTxNOK(long l) ;
        public void sampleRefillInformationLatencyRxNOK(long l) ;
	
        public void incrementRefillValueTotalTxOK(long l) ;
        public void incrementRefillValueTotalRxOK(long l) ;
        public void incrementRefillValueTotalTxNOK(long l) ;
        public void incrementRefillValueTotalRxNOK(long l) ;
        public long getRefillValueTotalTxOK() ;
        public long getRefillValueTotalRxOK() ;
        public long getRefillValueTotalTxNOK() ;
        public long getRefillValueTotalRxNOK() ;
        public SampleStatistics getRefillValueTotalLatencyTxOK() ;
        public SampleStatistics getRefillValueTotalLatencyRxOK() ;
        public SampleStatistics getRefillValueTotalLatencyTxNOK() ;
        public SampleStatistics getRefillValueTotalLatencyRxNOK() ;
        public void sampleRefillValueTotalLatencyTxOK(long l) ;
        public void sampleRefillValueTotalLatencyRxOK(long l) ;
        public void sampleRefillValueTotalLatencyTxNOK(long l) ;
        public void sampleRefillValueTotalLatencyRxNOK(long l) ;
	
        public void incrementRefillValuePromotionTxOK(long l) ;
        public void incrementRefillValuePromotionRxOK(long l) ;
        public void incrementRefillValuePromotionTxNOK(long l) ;
        public void incrementRefillValuePromotionRxNOK(long l) ;
        public long getRefillValuePromotionTxOK() ;
        public long getRefillValuePromotionRxOK() ;
        public long getRefillValuePromotionTxNOK() ;
        public long getRefillValuePromotionRxNOK() ;
        public SampleStatistics getRefillValuePromotionLatencyTxOK() ;
        public SampleStatistics getRefillValuePromotionLatencyRxOK() ;
        public SampleStatistics getRefillValuePromotionLatencyTxNOK() ;
        public SampleStatistics getRefillValuePromotionLatencyRxNOK() ;
        public void sampleRefillValuePromotionLatencyTxOK(long l) ;
        public void sampleRefillValuePromotionLatencyRxOK(long l) ;
        public void sampleRefillValuePromotionLatencyTxNOK(long l) ;
        public void sampleRefillValuePromotionLatencyRxNOK(long l) ;
	
        public void incrementDedicatedAccountRefillInformationTxOK(long l) ;
        public void incrementDedicatedAccountRefillInformationRxOK(long l) ;
        public void incrementDedicatedAccountRefillInformationTxNOK(long l) ;
        public void incrementDedicatedAccountRefillInformationRxNOK(long l) ;
        public long getDedicatedAccountRefillInformationTxOK() ;
        public long getDedicatedAccountRefillInformationRxOK() ;
        public long getDedicatedAccountRefillInformationTxNOK() ;
        public long getDedicatedAccountRefillInformationRxNOK() ;
        public SampleStatistics getDedicatedAccountRefillInformationLatencyTxOK() ;
        public SampleStatistics getDedicatedAccountRefillInformationLatencyRxOK() ;
        public SampleStatistics getDedicatedAccountRefillInformationLatencyTxNOK() ;
        public SampleStatistics getDedicatedAccountRefillInformationLatencyRxNOK() ;
        public void sampleDedicatedAccountRefillInformationLatencyTxOK(long l) ;
        public void sampleDedicatedAccountRefillInformationLatencyRxOK(long l) ;
        public void sampleDedicatedAccountRefillInformationLatencyTxNOK(long l) ;
        public void sampleDedicatedAccountRefillInformationLatencyRxNOK(long l) ;
	
        public void incrementUsageAccumulatorInformationTxOK(long l) ;
        public void incrementUsageAccumulatorInformationRxOK(long l) ;
        public void incrementUsageAccumulatorInformationTxNOK(long l) ;
        public void incrementUsageAccumulatorInformationRxNOK(long l) ;
        public long getUsageAccumulatorInformationTxOK() ;
        public long getUsageAccumulatorInformationRxOK() ;
        public long getUsageAccumulatorInformationTxNOK() ;
        public long getUsageAccumulatorInformationRxNOK() ;
        public SampleStatistics getUsageAccumulatorInformationLatencyTxOK() ;
        public SampleStatistics getUsageAccumulatorInformationLatencyRxOK() ;
        public SampleStatistics getUsageAccumulatorInformationLatencyTxNOK() ;
        public SampleStatistics getUsageAccumulatorInformationLatencyRxNOK() ;
        public void sampleUsageAccumulatorInformationLatencyTxOK(long l) ;
        public void sampleUsageAccumulatorInformationLatencyRxOK(long l) ;
        public void sampleUsageAccumulatorInformationLatencyTxNOK(long l) ;
        public void sampleUsageAccumulatorInformationLatencyRxNOK(long l) ;
	
        public void incrementUpdateAccountDetailsTxOK(long l) ;
        public void incrementUpdateAccountDetailsRxOK(long l) ;
        public void incrementUpdateAccountDetailsTxNOK(long l) ;
        public void incrementUpdateAccountDetailsRxNOK(long l) ;
        public long getUpdateAccountDetailsTxOK() ;
        public long getUpdateAccountDetailsRxOK() ;
        public long getUpdateAccountDetailsTxNOK() ;
        public long getUpdateAccountDetailsRxNOK() ;
        public SampleStatistics getUpdateAccountDetailsLatencyTxOK() ;
        public SampleStatistics getUpdateAccountDetailsLatencyRxOK() ;
        public SampleStatistics getUpdateAccountDetailsLatencyTxNOK() ;
        public SampleStatistics getUpdateAccountDetailsLatencyRxNOK() ;
        public void sampleUpdateAccountDetailsLatencyTxOK(long l) ;
        public void sampleUpdateAccountDetailsLatencyRxOK(long l) ;
        public void sampleUpdateAccountDetailsLatencyTxNOK(long l) ;
        public void sampleUpdateAccountDetailsLatencyRxNOK(long l) ;
	
        public void incrementUpdateFaFListTxOK(long l) ;
        public void incrementUpdateFaFListRxOK(long l) ;
        public void incrementUpdateFaFListTxNOK(long l) ;
        public void incrementUpdateFaFListRxNOK(long l) ;
        public long getUpdateFaFListTxOK() ;
        public long getUpdateFaFListRxOK() ;
        public long getUpdateFaFListTxNOK() ;
        public long getUpdateFaFListRxNOK() ;
        public SampleStatistics getUpdateFaFListLatencyTxOK() ;
        public SampleStatistics getUpdateFaFListLatencyRxOK() ;
        public SampleStatistics getUpdateFaFListLatencyTxNOK() ;
        public SampleStatistics getUpdateFaFListLatencyRxNOK() ;
        public void sampleUpdateFaFListLatencyTxOK(long l) ;
        public void sampleUpdateFaFListLatencyRxOK(long l) ;
        public void sampleUpdateFaFListLatencyTxNOK(long l) ;
        public void sampleUpdateFaFListLatencyRxNOK(long l) ;
	
        public void incrementUpdateServiceClassTxOK(long l) ;
        public void incrementUpdateServiceClassRxOK(long l) ;
        public void incrementUpdateServiceClassTxNOK(long l) ;
        public void incrementUpdateServiceClassRxNOK(long l) ;
        public long getUpdateServiceClassTxOK() ;
        public long getUpdateServiceClassRxOK() ;
        public long getUpdateServiceClassTxNOK() ;
        public long getUpdateServiceClassRxNOK() ;
        public SampleStatistics getUpdateServiceClassLatencyTxOK() ;
        public SampleStatistics getUpdateServiceClassLatencyRxOK() ;
        public SampleStatistics getUpdateServiceClassLatencyTxNOK() ;
        public SampleStatistics getUpdateServiceClassLatencyRxNOK() ;
        public void sampleUpdateServiceClassLatencyTxOK(long l) ;
        public void sampleUpdateServiceClassLatencyRxOK(long l) ;
        public void sampleUpdateServiceClassLatencyTxNOK(long l) ;
        public void sampleUpdateServiceClassLatencyRxNOK(long l) ;
	
        public void incrementUpdateCommunityListTxOK(long l) ;
        public void incrementUpdateCommunityListRxOK(long l) ;
        public void incrementUpdateCommunityListTxNOK(long l) ;
        public void incrementUpdateCommunityListRxNOK(long l) ;
        public long getUpdateCommunityListTxOK() ;
        public long getUpdateCommunityListRxOK() ;
        public long getUpdateCommunityListTxNOK() ;
        public long getUpdateCommunityListRxNOK() ;
        public SampleStatistics getUpdateCommunityListLatencyTxOK() ;
        public SampleStatistics getUpdateCommunityListLatencyRxOK() ;
        public SampleStatistics getUpdateCommunityListLatencyTxNOK() ;
        public SampleStatistics getUpdateCommunityListLatencyRxNOK() ;
        public void sampleUpdateCommunityListLatencyTxOK(long l) ;
        public void sampleUpdateCommunityListLatencyRxOK(long l) ;
        public void sampleUpdateCommunityListLatencyTxNOK(long l) ;
        public void sampleUpdateCommunityListLatencyRxNOK(long l) ;
	
        public void incrementUpdateSubscriberSegmentationTxOK(long l) ;
        public void incrementUpdateSubscriberSegmentationRxOK(long l) ;
        public void incrementUpdateSubscriberSegmentationTxNOK(long l) ;
        public void incrementUpdateSubscriberSegmentationRxNOK(long l) ;
        public long getUpdateSubscriberSegmentationTxOK() ;
        public long getUpdateSubscriberSegmentationRxOK() ;
        public long getUpdateSubscriberSegmentationTxNOK() ;
        public long getUpdateSubscriberSegmentationRxNOK() ;
        public SampleStatistics getUpdateSubscriberSegmentationLatencyTxOK() ;
        public SampleStatistics getUpdateSubscriberSegmentationLatencyRxOK() ;
        public SampleStatistics getUpdateSubscriberSegmentationLatencyTxNOK() ;
        public SampleStatistics getUpdateSubscriberSegmentationLatencyRxNOK() ;
        public void sampleUpdateSubscriberSegmentationLatencyTxOK(long l) ;
        public void sampleUpdateSubscriberSegmentationLatencyRxOK(long l) ;
        public void sampleUpdateSubscriberSegmentationLatencyTxNOK(long l) ;
        public void sampleUpdateSubscriberSegmentationLatencyRxNOK(long l) ;
	
        public void incrementAccountFlagsTxOK(long l) ;
        public void incrementAccountFlagsRxOK(long l) ;
        public void incrementAccountFlagsTxNOK(long l) ;
        public void incrementAccountFlagsRxNOK(long l) ;
        public long getAccountFlagsTxOK() ;
        public long getAccountFlagsRxOK() ;
        public long getAccountFlagsTxNOK() ;
        public long getAccountFlagsRxNOK() ;
        public SampleStatistics getAccountFlagsLatencyTxOK() ;
        public SampleStatistics getAccountFlagsLatencyRxOK() ;
        public SampleStatistics getAccountFlagsLatencyTxNOK() ;
        public SampleStatistics getAccountFlagsLatencyRxNOK() ;
        public void sampleAccountFlagsLatencyTxOK(long l) ;
        public void sampleAccountFlagsLatencyRxOK(long l) ;
        public void sampleAccountFlagsLatencyTxNOK(long l) ;
        public void sampleAccountFlagsLatencyRxNOK(long l) ;
	
        public void incrementAccumulatorSelectionTxOK(long l) ;
        public void incrementAccumulatorSelectionRxOK(long l) ;
        public void incrementAccumulatorSelectionTxNOK(long l) ;
        public void incrementAccumulatorSelectionRxNOK(long l) ;
        public long getAccumulatorSelectionTxOK() ;
        public long getAccumulatorSelectionRxOK() ;
        public long getAccumulatorSelectionTxNOK() ;
        public long getAccumulatorSelectionRxNOK() ;
        public SampleStatistics getAccumulatorSelectionLatencyTxOK() ;
        public SampleStatistics getAccumulatorSelectionLatencyRxOK() ;
        public SampleStatistics getAccumulatorSelectionLatencyTxNOK() ;
        public SampleStatistics getAccumulatorSelectionLatencyRxNOK() ;
        public void sampleAccumulatorSelectionLatencyTxOK(long l) ;
        public void sampleAccumulatorSelectionLatencyRxOK(long l) ;
        public void sampleAccumulatorSelectionLatencyTxNOK(long l) ;
        public void sampleAccumulatorSelectionLatencyRxNOK(long l) ;
	
        public void incrementChargingRequestInformationTxOK(long l) ;
        public void incrementChargingRequestInformationRxOK(long l) ;
        public void incrementChargingRequestInformationTxNOK(long l) ;
        public void incrementChargingRequestInformationRxNOK(long l) ;
        public long getChargingRequestInformationTxOK() ;
        public long getChargingRequestInformationRxOK() ;
        public long getChargingRequestInformationTxNOK() ;
        public long getChargingRequestInformationRxNOK() ;
        public SampleStatistics getChargingRequestInformationLatencyTxOK() ;
        public SampleStatistics getChargingRequestInformationLatencyRxOK() ;
        public SampleStatistics getChargingRequestInformationLatencyTxNOK() ;
        public SampleStatistics getChargingRequestInformationLatencyRxNOK() ;
        public void sampleChargingRequestInformationLatencyTxOK(long l) ;
        public void sampleChargingRequestInformationLatencyRxOK(long l) ;
        public void sampleChargingRequestInformationLatencyTxNOK(long l) ;
        public void sampleChargingRequestInformationLatencyRxNOK(long l) ;
	
        public void incrementChargingResultInformationTxOK(long l) ;
        public void incrementChargingResultInformationRxOK(long l) ;
        public void incrementChargingResultInformationTxNOK(long l) ;
        public void incrementChargingResultInformationRxNOK(long l) ;
        public long getChargingResultInformationTxOK() ;
        public long getChargingResultInformationRxOK() ;
        public long getChargingResultInformationTxNOK() ;
        public long getChargingResultInformationRxNOK() ;
        public SampleStatistics getChargingResultInformationLatencyTxOK() ;
        public SampleStatistics getChargingResultInformationLatencyRxOK() ;
        public SampleStatistics getChargingResultInformationLatencyTxNOK() ;
        public SampleStatistics getChargingResultInformationLatencyRxNOK() ;
        public void sampleChargingResultInformationLatencyTxOK(long l) ;
        public void sampleChargingResultInformationLatencyRxOK(long l) ;
        public void sampleChargingResultInformationLatencyTxNOK(long l) ;
        public void sampleChargingResultInformationLatencyRxNOK(long l) ;
	
        public void incrementChargingResultInformationServiceTxOK(long l) ;
        public void incrementChargingResultInformationServiceRxOK(long l) ;
        public void incrementChargingResultInformationServiceTxNOK(long l) ;
        public void incrementChargingResultInformationServiceRxNOK(long l) ;
        public long getChargingResultInformationServiceTxOK() ;
        public long getChargingResultInformationServiceRxOK() ;
        public long getChargingResultInformationServiceTxNOK() ;
        public long getChargingResultInformationServiceRxNOK() ;
        public SampleStatistics getChargingResultInformationServiceLatencyTxOK() ;
        public SampleStatistics getChargingResultInformationServiceLatencyRxOK() ;
        public SampleStatistics getChargingResultInformationServiceLatencyTxNOK() ;
        public SampleStatistics getChargingResultInformationServiceLatencyRxNOK() ;
        public void sampleChargingResultInformationServiceLatencyTxOK(long l) ;
        public void sampleChargingResultInformationServiceLatencyRxOK(long l) ;
        public void sampleChargingResultInformationServiceLatencyTxNOK(long l) ;
        public void sampleChargingResultInformationServiceLatencyRxNOK(long l) ;
	
        public void incrementCommunityIdListTxOK(long l) ;
        public void incrementCommunityIdListRxOK(long l) ;
        public void incrementCommunityIdListTxNOK(long l) ;
        public void incrementCommunityIdListRxNOK(long l) ;
        public long getCommunityIdListTxOK() ;
        public long getCommunityIdListRxOK() ;
        public long getCommunityIdListTxNOK() ;
        public long getCommunityIdListRxNOK() ;
        public SampleStatistics getCommunityIdListLatencyTxOK() ;
        public SampleStatistics getCommunityIdListLatencyRxOK() ;
        public SampleStatistics getCommunityIdListLatencyTxNOK() ;
        public SampleStatistics getCommunityIdListLatencyRxNOK() ;
        public void sampleCommunityIdListLatencyTxOK(long l) ;
        public void sampleCommunityIdListLatencyRxOK(long l) ;
        public void sampleCommunityIdListLatencyTxNOK(long l) ;
        public void sampleCommunityIdListLatencyRxNOK(long l) ;
	
        public void incrementCommunityInformationCurrentTxOK(long l) ;
        public void incrementCommunityInformationCurrentRxOK(long l) ;
        public void incrementCommunityInformationCurrentTxNOK(long l) ;
        public void incrementCommunityInformationCurrentRxNOK(long l) ;
        public long getCommunityInformationCurrentTxOK() ;
        public long getCommunityInformationCurrentRxOK() ;
        public long getCommunityInformationCurrentTxNOK() ;
        public long getCommunityInformationCurrentRxNOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyTxOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyRxOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyTxNOK() ;
        public SampleStatistics getCommunityInformationCurrentLatencyRxNOK() ;
        public void sampleCommunityInformationCurrentLatencyTxOK(long l) ;
        public void sampleCommunityInformationCurrentLatencyRxOK(long l) ;
        public void sampleCommunityInformationCurrentLatencyTxNOK(long l) ;
        public void sampleCommunityInformationCurrentLatencyRxNOK(long l) ;
	
        public void incrementCommunityInformationNewTxOK(long l) ;
        public void incrementCommunityInformationNewRxOK(long l) ;
        public void incrementCommunityInformationNewTxNOK(long l) ;
        public void incrementCommunityInformationNewRxNOK(long l) ;
        public long getCommunityInformationNewTxOK() ;
        public long getCommunityInformationNewRxOK() ;
        public long getCommunityInformationNewTxNOK() ;
        public long getCommunityInformationNewRxNOK() ;
        public SampleStatistics getCommunityInformationNewLatencyTxOK() ;
        public SampleStatistics getCommunityInformationNewLatencyRxOK() ;
        public SampleStatistics getCommunityInformationNewLatencyTxNOK() ;
        public SampleStatistics getCommunityInformationNewLatencyRxNOK() ;
        public void sampleCommunityInformationNewLatencyTxOK(long l) ;
        public void sampleCommunityInformationNewLatencyRxOK(long l) ;
        public void sampleCommunityInformationNewLatencyTxNOK(long l) ;
        public void sampleCommunityInformationNewLatencyRxNOK(long l) ;
	
        public void incrementDedicatedAccountInformationTxOK(long l) ;
        public void incrementDedicatedAccountInformationRxOK(long l) ;
        public void incrementDedicatedAccountInformationTxNOK(long l) ;
        public void incrementDedicatedAccountInformationRxNOK(long l) ;
        public long getDedicatedAccountInformationTxOK() ;
        public long getDedicatedAccountInformationRxOK() ;
        public long getDedicatedAccountInformationTxNOK() ;
        public long getDedicatedAccountInformationRxNOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyTxOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyRxOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyTxNOK() ;
        public SampleStatistics getDedicatedAccountInformationLatencyRxNOK() ;
        public void sampleDedicatedAccountInformationLatencyTxOK(long l) ;
        public void sampleDedicatedAccountInformationLatencyRxOK(long l) ;
        public void sampleDedicatedAccountInformationLatencyTxNOK(long l) ;
        public void sampleDedicatedAccountInformationLatencyRxNOK(long l) ;
	
        public void incrementDedicatedAccountSelectionTxOK(long l) ;
        public void incrementDedicatedAccountSelectionRxOK(long l) ;
        public void incrementDedicatedAccountSelectionTxNOK(long l) ;
        public void incrementDedicatedAccountSelectionRxNOK(long l) ;
        public long getDedicatedAccountSelectionTxOK() ;
        public long getDedicatedAccountSelectionRxOK() ;
        public long getDedicatedAccountSelectionTxNOK() ;
        public long getDedicatedAccountSelectionRxNOK() ;
        public SampleStatistics getDedicatedAccountSelectionLatencyTxOK() ;
        public SampleStatistics getDedicatedAccountSelectionLatencyRxOK() ;
        public SampleStatistics getDedicatedAccountSelectionLatencyTxNOK() ;
        public SampleStatistics getDedicatedAccountSelectionLatencyRxNOK() ;
        public void sampleDedicatedAccountSelectionLatencyTxOK(long l) ;
        public void sampleDedicatedAccountSelectionLatencyRxOK(long l) ;
        public void sampleDedicatedAccountSelectionLatencyTxNOK(long l) ;
        public void sampleDedicatedAccountSelectionLatencyRxNOK(long l) ;
	
        public void incrementFafInformationTxOK(long l) ;
        public void incrementFafInformationRxOK(long l) ;
        public void incrementFafInformationTxNOK(long l) ;
        public void incrementFafInformationRxNOK(long l) ;
        public long getFafInformationTxOK() ;
        public long getFafInformationRxOK() ;
        public long getFafInformationTxNOK() ;
        public long getFafInformationRxNOK() ;
        public SampleStatistics getFafInformationLatencyTxOK() ;
        public SampleStatistics getFafInformationLatencyRxOK() ;
        public SampleStatistics getFafInformationLatencyTxNOK() ;
        public SampleStatistics getFafInformationLatencyRxNOK() ;
        public void sampleFafInformationLatencyTxOK(long l) ;
        public void sampleFafInformationLatencyRxOK(long l) ;
        public void sampleFafInformationLatencyTxNOK(long l) ;
        public void sampleFafInformationLatencyRxNOK(long l) ;
	
        public void incrementFafInformationListTxOK(long l) ;
        public void incrementFafInformationListRxOK(long l) ;
        public void incrementFafInformationListTxNOK(long l) ;
        public void incrementFafInformationListRxNOK(long l) ;
        public long getFafInformationListTxOK() ;
        public long getFafInformationListRxOK() ;
        public long getFafInformationListTxNOK() ;
        public long getFafInformationListRxNOK() ;
        public SampleStatistics getFafInformationListLatencyTxOK() ;
        public SampleStatistics getFafInformationListLatencyRxOK() ;
        public SampleStatistics getFafInformationListLatencyTxNOK() ;
        public SampleStatistics getFafInformationListLatencyRxNOK() ;
        public void sampleFafInformationListLatencyTxOK(long l) ;
        public void sampleFafInformationListLatencyRxOK(long l) ;
        public void sampleFafInformationListLatencyTxNOK(long l) ;
        public void sampleFafInformationListLatencyRxNOK(long l) ;
	
        public void incrementMessageCapabilityFlagTxOK(long l) ;
        public void incrementMessageCapabilityFlagRxOK(long l) ;
        public void incrementMessageCapabilityFlagTxNOK(long l) ;
        public void incrementMessageCapabilityFlagRxNOK(long l) ;
        public long getMessageCapabilityFlagTxOK() ;
        public long getMessageCapabilityFlagRxOK() ;
        public long getMessageCapabilityFlagTxNOK() ;
        public long getMessageCapabilityFlagRxNOK() ;
        public SampleStatistics getMessageCapabilityFlagLatencyTxOK() ;
        public SampleStatistics getMessageCapabilityFlagLatencyRxOK() ;
        public SampleStatistics getMessageCapabilityFlagLatencyTxNOK() ;
        public SampleStatistics getMessageCapabilityFlagLatencyRxNOK() ;
        public void sampleMessageCapabilityFlagLatencyTxOK(long l) ;
        public void sampleMessageCapabilityFlagLatencyRxOK(long l) ;
        public void sampleMessageCapabilityFlagLatencyTxNOK(long l) ;
        public void sampleMessageCapabilityFlagLatencyRxNOK(long l) ;
	
        public void incrementRequestedInformationFlagsTxOK(long l) ;
        public void incrementRequestedInformationFlagsRxOK(long l) ;
        public void incrementRequestedInformationFlagsTxNOK(long l) ;
        public void incrementRequestedInformationFlagsRxNOK(long l) ;
        public long getRequestedInformationFlagsTxOK() ;
        public long getRequestedInformationFlagsRxOK() ;
        public long getRequestedInformationFlagsTxNOK() ;
        public long getRequestedInformationFlagsRxNOK() ;
        public SampleStatistics getRequestedInformationFlagsLatencyTxOK() ;
        public SampleStatistics getRequestedInformationFlagsLatencyRxOK() ;
        public SampleStatistics getRequestedInformationFlagsLatencyTxNOK() ;
        public SampleStatistics getRequestedInformationFlagsLatencyRxNOK() ;
        public void sampleRequestedInformationFlagsLatencyTxOK(long l) ;
        public void sampleRequestedInformationFlagsLatencyRxOK(long l) ;
        public void sampleRequestedInformationFlagsLatencyTxNOK(long l) ;
        public void sampleRequestedInformationFlagsLatencyRxNOK(long l) ;
	
        public void incrementServiceOfferingsTxOK(long l) ;
        public void incrementServiceOfferingsRxOK(long l) ;
        public void incrementServiceOfferingsTxNOK(long l) ;
        public void incrementServiceOfferingsRxNOK(long l) ;
        public long getServiceOfferingsTxOK() ;
        public long getServiceOfferingsRxOK() ;
        public long getServiceOfferingsTxNOK() ;
        public long getServiceOfferingsRxNOK() ;
        public SampleStatistics getServiceOfferingsLatencyTxOK() ;
        public SampleStatistics getServiceOfferingsLatencyRxOK() ;
        public SampleStatistics getServiceOfferingsLatencyTxNOK() ;
        public SampleStatistics getServiceOfferingsLatencyRxNOK() ;
        public void sampleServiceOfferingsLatencyTxOK(long l) ;
        public void sampleServiceOfferingsLatencyRxOK(long l) ;
        public void sampleServiceOfferingsLatencyTxNOK(long l) ;
        public void sampleServiceOfferingsLatencyRxNOK(long l) ;
	
        }
