	
          package mofokom.ccn.vs.vsip.resource;
          import javax.annotation.Generated;
          import javax.slee.usage.SampleStatistics;
          import mofokom.ccn.resource.ResourceAdaptorUsageParameters;
          @Generated(value={})
          public interface VSIPResourceAdaptorUsageParameters extends ResourceAdaptorUsageParameters {
        public void incrementTxOK(long l) ;
        public void incrementRxOK(long l) ;
        public void incrementTxNOK(long l) ;
        public void incrementRxNOK(long l) ;
        public long getTxOK() ;
        public long getRxOK() ;
        public long getTxNOK() ;
        public long getRxNOK() ;
        public SampleStatistics getLatencyTxOK() ;
        public SampleStatistics getLatencyRxOK() ;
        public SampleStatistics getLatencyTxNOK() ;
        public SampleStatistics getLatencyRxNOK() ;
        public void sampleLatencyTxOK(long l) ;
        public void sampleLatencyRxOK(long l) ;
        public void sampleLatencyTxNOK(long l) ;
        public void sampleLatencyRxNOK(long l) ;
        public void incrementFaultTxOK(long l) ;
        public void incrementFaultRxOK(long l) ;
        public void incrementFaultTxNOK(long l) ;
        public void incrementFaultRxNOK(long l) ;
        public long getFaultTxOK() ;
        public long getFaultRxOK() ;
        public long getFaultTxNOK() ;
        public long getFaultRxNOK() ;
        public SampleStatistics getFaultLatencyTxOK() ;
        public SampleStatistics getFaultLatencyRxOK() ;
        public SampleStatistics getFaultLatencyTxNOK() ;
        public SampleStatistics getFaultLatencyRxNOK() ;
        public void sampleFaultLatencyTxOK(long l) ;
        public void sampleFaultLatencyRxOK(long l) ;
        public void sampleFaultLatencyTxNOK(long l) ;
        public void sampleFaultLatencyRxNOK(long l) ;
	
        public void incrementGetVoucherDetailsTxOK(long l) ;
        public void incrementGetVoucherDetailsRxOK(long l) ;
        public void incrementGetVoucherDetailsTxNOK(long l) ;
        public void incrementGetVoucherDetailsRxNOK(long l) ;
        public long getGetVoucherDetailsTxOK() ;
        public long getGetVoucherDetailsRxOK() ;
        public long getGetVoucherDetailsTxNOK() ;
        public long getGetVoucherDetailsRxNOK() ;
        public SampleStatistics getGetVoucherDetailsLatencyTxOK() ;
        public SampleStatistics getGetVoucherDetailsLatencyRxOK() ;
        public SampleStatistics getGetVoucherDetailsLatencyTxNOK() ;
        public SampleStatistics getGetVoucherDetailsLatencyRxNOK() ;
        public void sampleGetVoucherDetailsLatencyTxOK(long l) ;
        public void sampleGetVoucherDetailsLatencyRxOK(long l) ;
        public void sampleGetVoucherDetailsLatencyTxNOK(long l) ;
        public void sampleGetVoucherDetailsLatencyRxNOK(long l) ;
	
        public void incrementGetVoucherHistoryTxOK(long l) ;
        public void incrementGetVoucherHistoryRxOK(long l) ;
        public void incrementGetVoucherHistoryTxNOK(long l) ;
        public void incrementGetVoucherHistoryRxNOK(long l) ;
        public long getGetVoucherHistoryTxOK() ;
        public long getGetVoucherHistoryRxOK() ;
        public long getGetVoucherHistoryTxNOK() ;
        public long getGetVoucherHistoryRxNOK() ;
        public SampleStatistics getGetVoucherHistoryLatencyTxOK() ;
        public SampleStatistics getGetVoucherHistoryLatencyRxOK() ;
        public SampleStatistics getGetVoucherHistoryLatencyTxNOK() ;
        public SampleStatistics getGetVoucherHistoryLatencyRxNOK() ;
        public void sampleGetVoucherHistoryLatencyTxOK(long l) ;
        public void sampleGetVoucherHistoryLatencyRxOK(long l) ;
        public void sampleGetVoucherHistoryLatencyTxNOK(long l) ;
        public void sampleGetVoucherHistoryLatencyRxNOK(long l) ;
	
        public void incrementUpdateVoucherStateTxOK(long l) ;
        public void incrementUpdateVoucherStateRxOK(long l) ;
        public void incrementUpdateVoucherStateTxNOK(long l) ;
        public void incrementUpdateVoucherStateRxNOK(long l) ;
        public long getUpdateVoucherStateTxOK() ;
        public long getUpdateVoucherStateRxOK() ;
        public long getUpdateVoucherStateTxNOK() ;
        public long getUpdateVoucherStateRxNOK() ;
        public SampleStatistics getUpdateVoucherStateLatencyTxOK() ;
        public SampleStatistics getUpdateVoucherStateLatencyRxOK() ;
        public SampleStatistics getUpdateVoucherStateLatencyTxNOK() ;
        public SampleStatistics getUpdateVoucherStateLatencyRxNOK() ;
        public void sampleUpdateVoucherStateLatencyTxOK(long l) ;
        public void sampleUpdateVoucherStateLatencyRxOK(long l) ;
        public void sampleUpdateVoucherStateLatencyTxNOK(long l) ;
        public void sampleUpdateVoucherStateLatencyRxNOK(long l) ;
	
        public void incrementLoadVoucherCheckTxOK(long l) ;
        public void incrementLoadVoucherCheckRxOK(long l) ;
        public void incrementLoadVoucherCheckTxNOK(long l) ;
        public void incrementLoadVoucherCheckRxNOK(long l) ;
        public long getLoadVoucherCheckTxOK() ;
        public long getLoadVoucherCheckRxOK() ;
        public long getLoadVoucherCheckTxNOK() ;
        public long getLoadVoucherCheckRxNOK() ;
        public SampleStatistics getLoadVoucherCheckLatencyTxOK() ;
        public SampleStatistics getLoadVoucherCheckLatencyRxOK() ;
        public SampleStatistics getLoadVoucherCheckLatencyTxNOK() ;
        public SampleStatistics getLoadVoucherCheckLatencyRxNOK() ;
        public void sampleLoadVoucherCheckLatencyTxOK(long l) ;
        public void sampleLoadVoucherCheckLatencyRxOK(long l) ;
        public void sampleLoadVoucherCheckLatencyTxNOK(long l) ;
        public void sampleLoadVoucherCheckLatencyRxNOK(long l) ;
	
        public void incrementGenerateVoucherTxOK(long l) ;
        public void incrementGenerateVoucherRxOK(long l) ;
        public void incrementGenerateVoucherTxNOK(long l) ;
        public void incrementGenerateVoucherRxNOK(long l) ;
        public long getGenerateVoucherTxOK() ;
        public long getGenerateVoucherRxOK() ;
        public long getGenerateVoucherTxNOK() ;
        public long getGenerateVoucherRxNOK() ;
        public SampleStatistics getGenerateVoucherLatencyTxOK() ;
        public SampleStatistics getGenerateVoucherLatencyRxOK() ;
        public SampleStatistics getGenerateVoucherLatencyTxNOK() ;
        public SampleStatistics getGenerateVoucherLatencyRxNOK() ;
        public void sampleGenerateVoucherLatencyTxOK(long l) ;
        public void sampleGenerateVoucherLatencyRxOK(long l) ;
        public void sampleGenerateVoucherLatencyTxNOK(long l) ;
        public void sampleGenerateVoucherLatencyRxNOK(long l) ;
	
        public void incrementGetGenerateVoucherTaskInfoTxOK(long l) ;
        public void incrementGetGenerateVoucherTaskInfoRxOK(long l) ;
        public void incrementGetGenerateVoucherTaskInfoTxNOK(long l) ;
        public void incrementGetGenerateVoucherTaskInfoRxNOK(long l) ;
        public long getGetGenerateVoucherTaskInfoTxOK() ;
        public long getGetGenerateVoucherTaskInfoRxOK() ;
        public long getGetGenerateVoucherTaskInfoTxNOK() ;
        public long getGetGenerateVoucherTaskInfoRxNOK() ;
        public SampleStatistics getGetGenerateVoucherTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetGenerateVoucherTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetGenerateVoucherTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetGenerateVoucherTaskInfoLatencyRxNOK() ;
        public void sampleGetGenerateVoucherTaskInfoLatencyTxOK(long l) ;
        public void sampleGetGenerateVoucherTaskInfoLatencyRxOK(long l) ;
        public void sampleGetGenerateVoucherTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetGenerateVoucherTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementLoadVoucherBatchFileTxOK(long l) ;
        public void incrementLoadVoucherBatchFileRxOK(long l) ;
        public void incrementLoadVoucherBatchFileTxNOK(long l) ;
        public void incrementLoadVoucherBatchFileRxNOK(long l) ;
        public long getLoadVoucherBatchFileTxOK() ;
        public long getLoadVoucherBatchFileRxOK() ;
        public long getLoadVoucherBatchFileTxNOK() ;
        public long getLoadVoucherBatchFileRxNOK() ;
        public SampleStatistics getLoadVoucherBatchFileLatencyTxOK() ;
        public SampleStatistics getLoadVoucherBatchFileLatencyRxOK() ;
        public SampleStatistics getLoadVoucherBatchFileLatencyTxNOK() ;
        public SampleStatistics getLoadVoucherBatchFileLatencyRxNOK() ;
        public void sampleLoadVoucherBatchFileLatencyTxOK(long l) ;
        public void sampleLoadVoucherBatchFileLatencyRxOK(long l) ;
        public void sampleLoadVoucherBatchFileLatencyTxNOK(long l) ;
        public void sampleLoadVoucherBatchFileLatencyRxNOK(long l) ;
	
        public void incrementGetLoadVoucherBatchFileTaskInfoTxOK(long l) ;
        public void incrementGetLoadVoucherBatchFileTaskInfoRxOK(long l) ;
        public void incrementGetLoadVoucherBatchFileTaskInfoTxNOK(long l) ;
        public void incrementGetLoadVoucherBatchFileTaskInfoRxNOK(long l) ;
        public long getGetLoadVoucherBatchFileTaskInfoTxOK() ;
        public long getGetLoadVoucherBatchFileTaskInfoRxOK() ;
        public long getGetLoadVoucherBatchFileTaskInfoTxNOK() ;
        public long getGetLoadVoucherBatchFileTaskInfoRxNOK() ;
        public SampleStatistics getGetLoadVoucherBatchFileTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetLoadVoucherBatchFileTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetLoadVoucherBatchFileTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetLoadVoucherBatchFileTaskInfoLatencyRxNOK() ;
        public void sampleGetLoadVoucherBatchFileTaskInfoLatencyTxOK(long l) ;
        public void sampleGetLoadVoucherBatchFileTaskInfoLatencyRxOK(long l) ;
        public void sampleGetLoadVoucherBatchFileTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetLoadVoucherBatchFileTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementGetVoucherBatchFilesListTxOK(long l) ;
        public void incrementGetVoucherBatchFilesListRxOK(long l) ;
        public void incrementGetVoucherBatchFilesListTxNOK(long l) ;
        public void incrementGetVoucherBatchFilesListRxNOK(long l) ;
        public long getGetVoucherBatchFilesListTxOK() ;
        public long getGetVoucherBatchFilesListRxOK() ;
        public long getGetVoucherBatchFilesListTxNOK() ;
        public long getGetVoucherBatchFilesListRxNOK() ;
        public SampleStatistics getGetVoucherBatchFilesListLatencyTxOK() ;
        public SampleStatistics getGetVoucherBatchFilesListLatencyRxOK() ;
        public SampleStatistics getGetVoucherBatchFilesListLatencyTxNOK() ;
        public SampleStatistics getGetVoucherBatchFilesListLatencyRxNOK() ;
        public void sampleGetVoucherBatchFilesListLatencyTxOK(long l) ;
        public void sampleGetVoucherBatchFilesListLatencyRxOK(long l) ;
        public void sampleGetVoucherBatchFilesListLatencyTxNOK(long l) ;
        public void sampleGetVoucherBatchFilesListLatencyRxNOK(long l) ;
	
        public void incrementChangeVoucherStateTxOK(long l) ;
        public void incrementChangeVoucherStateRxOK(long l) ;
        public void incrementChangeVoucherStateTxNOK(long l) ;
        public void incrementChangeVoucherStateRxNOK(long l) ;
        public long getChangeVoucherStateTxOK() ;
        public long getChangeVoucherStateRxOK() ;
        public long getChangeVoucherStateTxNOK() ;
        public long getChangeVoucherStateRxNOK() ;
        public SampleStatistics getChangeVoucherStateLatencyTxOK() ;
        public SampleStatistics getChangeVoucherStateLatencyRxOK() ;
        public SampleStatistics getChangeVoucherStateLatencyTxNOK() ;
        public SampleStatistics getChangeVoucherStateLatencyRxNOK() ;
        public void sampleChangeVoucherStateLatencyTxOK(long l) ;
        public void sampleChangeVoucherStateLatencyRxOK(long l) ;
        public void sampleChangeVoucherStateLatencyTxNOK(long l) ;
        public void sampleChangeVoucherStateLatencyRxNOK(long l) ;
	
        public void incrementGetChangeVoucherStateTaskInfoTxOK(long l) ;
        public void incrementGetChangeVoucherStateTaskInfoRxOK(long l) ;
        public void incrementGetChangeVoucherStateTaskInfoTxNOK(long l) ;
        public void incrementGetChangeVoucherStateTaskInfoRxNOK(long l) ;
        public long getGetChangeVoucherStateTaskInfoTxOK() ;
        public long getGetChangeVoucherStateTaskInfoRxOK() ;
        public long getGetChangeVoucherStateTaskInfoTxNOK() ;
        public long getGetChangeVoucherStateTaskInfoRxNOK() ;
        public SampleStatistics getGetChangeVoucherStateTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetChangeVoucherStateTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetChangeVoucherStateTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetChangeVoucherStateTaskInfoLatencyRxNOK() ;
        public void sampleGetChangeVoucherStateTaskInfoLatencyTxOK(long l) ;
        public void sampleGetChangeVoucherStateTaskInfoLatencyRxOK(long l) ;
        public void sampleGetChangeVoucherStateTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetChangeVoucherStateTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementPurgeVouchersTxOK(long l) ;
        public void incrementPurgeVouchersRxOK(long l) ;
        public void incrementPurgeVouchersTxNOK(long l) ;
        public void incrementPurgeVouchersRxNOK(long l) ;
        public long getPurgeVouchersTxOK() ;
        public long getPurgeVouchersRxOK() ;
        public long getPurgeVouchersTxNOK() ;
        public long getPurgeVouchersRxNOK() ;
        public SampleStatistics getPurgeVouchersLatencyTxOK() ;
        public SampleStatistics getPurgeVouchersLatencyRxOK() ;
        public SampleStatistics getPurgeVouchersLatencyTxNOK() ;
        public SampleStatistics getPurgeVouchersLatencyRxNOK() ;
        public void samplePurgeVouchersLatencyTxOK(long l) ;
        public void samplePurgeVouchersLatencyRxOK(long l) ;
        public void samplePurgeVouchersLatencyTxNOK(long l) ;
        public void samplePurgeVouchersLatencyRxNOK(long l) ;
	
        public void incrementGetPurgeVouchersTaskInfoTxOK(long l) ;
        public void incrementGetPurgeVouchersTaskInfoRxOK(long l) ;
        public void incrementGetPurgeVouchersTaskInfoTxNOK(long l) ;
        public void incrementGetPurgeVouchersTaskInfoRxNOK(long l) ;
        public long getGetPurgeVouchersTaskInfoTxOK() ;
        public long getGetPurgeVouchersTaskInfoRxOK() ;
        public long getGetPurgeVouchersTaskInfoTxNOK() ;
        public long getGetPurgeVouchersTaskInfoRxNOK() ;
        public SampleStatistics getGetPurgeVouchersTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetPurgeVouchersTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetPurgeVouchersTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetPurgeVouchersTaskInfoLatencyRxNOK() ;
        public void sampleGetPurgeVouchersTaskInfoLatencyTxOK(long l) ;
        public void sampleGetPurgeVouchersTaskInfoLatencyRxOK(long l) ;
        public void sampleGetPurgeVouchersTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetPurgeVouchersTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementGenerateVoucherDetailsReportTxOK(long l) ;
        public void incrementGenerateVoucherDetailsReportRxOK(long l) ;
        public void incrementGenerateVoucherDetailsReportTxNOK(long l) ;
        public void incrementGenerateVoucherDetailsReportRxNOK(long l) ;
        public long getGenerateVoucherDetailsReportTxOK() ;
        public long getGenerateVoucherDetailsReportRxOK() ;
        public long getGenerateVoucherDetailsReportTxNOK() ;
        public long getGenerateVoucherDetailsReportRxNOK() ;
        public SampleStatistics getGenerateVoucherDetailsReportLatencyTxOK() ;
        public SampleStatistics getGenerateVoucherDetailsReportLatencyRxOK() ;
        public SampleStatistics getGenerateVoucherDetailsReportLatencyTxNOK() ;
        public SampleStatistics getGenerateVoucherDetailsReportLatencyRxNOK() ;
        public void sampleGenerateVoucherDetailsReportLatencyTxOK(long l) ;
        public void sampleGenerateVoucherDetailsReportLatencyRxOK(long l) ;
        public void sampleGenerateVoucherDetailsReportLatencyTxNOK(long l) ;
        public void sampleGenerateVoucherDetailsReportLatencyRxNOK(long l) ;
	
        public void incrementGetGenerateVoucherDetailsReportTaskInfoTxOK(long l) ;
        public void incrementGetGenerateVoucherDetailsReportTaskInfoRxOK(long l) ;
        public void incrementGetGenerateVoucherDetailsReportTaskInfoTxNOK(long l) ;
        public void incrementGetGenerateVoucherDetailsReportTaskInfoRxNOK(long l) ;
        public long getGetGenerateVoucherDetailsReportTaskInfoTxOK() ;
        public long getGetGenerateVoucherDetailsReportTaskInfoRxOK() ;
        public long getGetGenerateVoucherDetailsReportTaskInfoTxNOK() ;
        public long getGetGenerateVoucherDetailsReportTaskInfoRxNOK() ;
        public SampleStatistics getGetGenerateVoucherDetailsReportTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetGenerateVoucherDetailsReportTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetGenerateVoucherDetailsReportTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetGenerateVoucherDetailsReportTaskInfoLatencyRxNOK() ;
        public void sampleGetGenerateVoucherDetailsReportTaskInfoLatencyTxOK(long l) ;
        public void sampleGetGenerateVoucherDetailsReportTaskInfoLatencyRxOK(long l) ;
        public void sampleGetGenerateVoucherDetailsReportTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetGenerateVoucherDetailsReportTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementGenerateVoucherDistributionReportTxOK(long l) ;
        public void incrementGenerateVoucherDistributionReportRxOK(long l) ;
        public void incrementGenerateVoucherDistributionReportTxNOK(long l) ;
        public void incrementGenerateVoucherDistributionReportRxNOK(long l) ;
        public long getGenerateVoucherDistributionReportTxOK() ;
        public long getGenerateVoucherDistributionReportRxOK() ;
        public long getGenerateVoucherDistributionReportTxNOK() ;
        public long getGenerateVoucherDistributionReportRxNOK() ;
        public SampleStatistics getGenerateVoucherDistributionReportLatencyTxOK() ;
        public SampleStatistics getGenerateVoucherDistributionReportLatencyRxOK() ;
        public SampleStatistics getGenerateVoucherDistributionReportLatencyTxNOK() ;
        public SampleStatistics getGenerateVoucherDistributionReportLatencyRxNOK() ;
        public void sampleGenerateVoucherDistributionReportLatencyTxOK(long l) ;
        public void sampleGenerateVoucherDistributionReportLatencyRxOK(long l) ;
        public void sampleGenerateVoucherDistributionReportLatencyTxNOK(long l) ;
        public void sampleGenerateVoucherDistributionReportLatencyRxNOK(long l) ;
	
        public void incrementGetGenerateVoucherDistributionReportTaskInfoTxOK(long l) ;
        public void incrementGetGenerateVoucherDistributionReportTaskInfoRxOK(long l) ;
        public void incrementGetGenerateVoucherDistributionReportTaskInfoTxNOK(long l) ;
        public void incrementGetGenerateVoucherDistributionReportTaskInfoRxNOK(long l) ;
        public long getGetGenerateVoucherDistributionReportTaskInfoTxOK() ;
        public long getGetGenerateVoucherDistributionReportTaskInfoRxOK() ;
        public long getGetGenerateVoucherDistributionReportTaskInfoTxNOK() ;
        public long getGetGenerateVoucherDistributionReportTaskInfoRxNOK() ;
        public SampleStatistics getGetGenerateVoucherDistributionReportTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetGenerateVoucherDistributionReportTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetGenerateVoucherDistributionReportTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetGenerateVoucherDistributionReportTaskInfoLatencyRxNOK() ;
        public void sampleGetGenerateVoucherDistributionReportTaskInfoLatencyTxOK(long l) ;
        public void sampleGetGenerateVoucherDistributionReportTaskInfoLatencyRxOK(long l) ;
        public void sampleGetGenerateVoucherDistributionReportTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetGenerateVoucherDistributionReportTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementGenerateVoucherUsageReportTxOK(long l) ;
        public void incrementGenerateVoucherUsageReportRxOK(long l) ;
        public void incrementGenerateVoucherUsageReportTxNOK(long l) ;
        public void incrementGenerateVoucherUsageReportRxNOK(long l) ;
        public long getGenerateVoucherUsageReportTxOK() ;
        public long getGenerateVoucherUsageReportRxOK() ;
        public long getGenerateVoucherUsageReportTxNOK() ;
        public long getGenerateVoucherUsageReportRxNOK() ;
        public SampleStatistics getGenerateVoucherUsageReportLatencyTxOK() ;
        public SampleStatistics getGenerateVoucherUsageReportLatencyRxOK() ;
        public SampleStatistics getGenerateVoucherUsageReportLatencyTxNOK() ;
        public SampleStatistics getGenerateVoucherUsageReportLatencyRxNOK() ;
        public void sampleGenerateVoucherUsageReportLatencyTxOK(long l) ;
        public void sampleGenerateVoucherUsageReportLatencyRxOK(long l) ;
        public void sampleGenerateVoucherUsageReportLatencyTxNOK(long l) ;
        public void sampleGenerateVoucherUsageReportLatencyRxNOK(long l) ;
	
        public void incrementGetGenerateVoucherUsageReportTaskInfoTxOK(long l) ;
        public void incrementGetGenerateVoucherUsageReportTaskInfoRxOK(long l) ;
        public void incrementGetGenerateVoucherUsageReportTaskInfoTxNOK(long l) ;
        public void incrementGetGenerateVoucherUsageReportTaskInfoRxNOK(long l) ;
        public long getGetGenerateVoucherUsageReportTaskInfoTxOK() ;
        public long getGetGenerateVoucherUsageReportTaskInfoRxOK() ;
        public long getGetGenerateVoucherUsageReportTaskInfoTxNOK() ;
        public long getGetGenerateVoucherUsageReportTaskInfoRxNOK() ;
        public SampleStatistics getGetGenerateVoucherUsageReportTaskInfoLatencyTxOK() ;
        public SampleStatistics getGetGenerateVoucherUsageReportTaskInfoLatencyRxOK() ;
        public SampleStatistics getGetGenerateVoucherUsageReportTaskInfoLatencyTxNOK() ;
        public SampleStatistics getGetGenerateVoucherUsageReportTaskInfoLatencyRxNOK() ;
        public void sampleGetGenerateVoucherUsageReportTaskInfoLatencyTxOK(long l) ;
        public void sampleGetGenerateVoucherUsageReportTaskInfoLatencyRxOK(long l) ;
        public void sampleGetGenerateVoucherUsageReportTaskInfoLatencyTxNOK(long l) ;
        public void sampleGetGenerateVoucherUsageReportTaskInfoLatencyRxNOK(long l) ;
	
        public void incrementDeleteTaskTxOK(long l) ;
        public void incrementDeleteTaskRxOK(long l) ;
        public void incrementDeleteTaskTxNOK(long l) ;
        public void incrementDeleteTaskRxNOK(long l) ;
        public long getDeleteTaskTxOK() ;
        public long getDeleteTaskRxOK() ;
        public long getDeleteTaskTxNOK() ;
        public long getDeleteTaskRxNOK() ;
        public SampleStatistics getDeleteTaskLatencyTxOK() ;
        public SampleStatistics getDeleteTaskLatencyRxOK() ;
        public SampleStatistics getDeleteTaskLatencyTxNOK() ;
        public SampleStatistics getDeleteTaskLatencyRxNOK() ;
        public void sampleDeleteTaskLatencyTxOK(long l) ;
        public void sampleDeleteTaskLatencyRxOK(long l) ;
        public void sampleDeleteTaskLatencyTxNOK(long l) ;
        public void sampleDeleteTaskLatencyRxNOK(long l) ;
	
        public void incrementReserveVoucherTxOK(long l) ;
        public void incrementReserveVoucherRxOK(long l) ;
        public void incrementReserveVoucherTxNOK(long l) ;
        public void incrementReserveVoucherRxNOK(long l) ;
        public long getReserveVoucherTxOK() ;
        public long getReserveVoucherRxOK() ;
        public long getReserveVoucherTxNOK() ;
        public long getReserveVoucherRxNOK() ;
        public SampleStatistics getReserveVoucherLatencyTxOK() ;
        public SampleStatistics getReserveVoucherLatencyRxOK() ;
        public SampleStatistics getReserveVoucherLatencyTxNOK() ;
        public SampleStatistics getReserveVoucherLatencyRxNOK() ;
        public void sampleReserveVoucherLatencyTxOK(long l) ;
        public void sampleReserveVoucherLatencyRxOK(long l) ;
        public void sampleReserveVoucherLatencyTxNOK(long l) ;
        public void sampleReserveVoucherLatencyRxNOK(long l) ;
	
        public void incrementEndReservationTxOK(long l) ;
        public void incrementEndReservationRxOK(long l) ;
        public void incrementEndReservationTxNOK(long l) ;
        public void incrementEndReservationRxNOK(long l) ;
        public long getEndReservationTxOK() ;
        public long getEndReservationRxOK() ;
        public long getEndReservationTxNOK() ;
        public long getEndReservationRxNOK() ;
        public SampleStatistics getEndReservationLatencyTxOK() ;
        public SampleStatistics getEndReservationLatencyRxOK() ;
        public SampleStatistics getEndReservationLatencyTxNOK() ;
        public SampleStatistics getEndReservationLatencyRxNOK() ;
        public void sampleEndReservationLatencyTxOK(long l) ;
        public void sampleEndReservationLatencyRxOK(long l) ;
        public void sampleEndReservationLatencyTxNOK(long l) ;
        public void sampleEndReservationLatencyRxNOK(long l) ;
	
        }
